### ISSUE TITLE
I can't connect to colab from G-Suite for education account.

### ISSUE THREAD

**Issue by SujinYoonKr** [googlecolab/colabtools#1065]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior: In a normal gmail account, I can open or create files in colab normally. However, my school's G Suite for Education account cannot suddenly open previously created files or create new files. Even though you are already logged in, a pop-up appears indicating that you need to log in.
Until last month, I used colab normally as an account in G Suite for Education. I think it might be a permission issue, so I added a colaboratory to Google Admin-App-Marketplace App and enabled it for all users.

- Describe the expected behavior: I want to use colab in class with my students.

- The web browser you are using: I use chrome browser.

- Link to self-contained notebook that reproduces this issue
  (click the *Share* button, then *Get Shareable Link*):

**Comment by BohnMods** [comment]
Having the exact issues, have you resolved it yet?

**Comment by SujinYoonKr** [comment]
> Having the exact issues, have you resolved it yet?

The problem is not solved.
The same thing happens when a teacher at another school logs in with his school's G Suite for Education account.
Currently, I'm instructing students to share the colab document they created in their G Suite account and use it as their regular gmail account.
Thank you for your attention.

**Comment by BohnMods** [comment]
That's unfortunate, looking forward to this.

**Comment by colaboratory-team** [comment]
Domain administrators must ensure that the toggle for "Access to additional services without individual control" is enabled in the Google Admin interface. See https://support.google.com/a/answer/7646040 for more information.

**Comment by SujinYoonKr** [comment]
> administrators
The issue has been resolved and Colab is available again in my school's G Suite account
Thank you so much.

**Comment by BohnMods** [comment]
> 
> 
> > administrators
> 
> The issue has been resolved and Colab is available again in my school's G Suite account
> Thank you so much.

Hello, glad to see that it worked out for you. But i'm confused, could you possibly take a screenshot and guide me what changes you made to make it work. 

Thanks.

**Comment by SujinYoonKr** [comment]
> > > administrators
> > 
> > 
> > The issue has been resolved and Colab is available again in my school's G Suite account
> > Thank you so much.
> 
> Hello, glad to see that it worked out for you. But i'm confused, could you possibly take a screenshot and guide me what changes you made to make it work.
> 
> Thanks.

I changed just one setting in the Google Admin console. I don't think the screenshots will help because the Google Admin console is interacting in Korean.
I changed the settings as below.

[Google Management Console]
    -[App]
       -[Additional Google services]
          -[Access to additional services is enabled without individual control of all organizational units]
             - [change]
                -[Enable all users]

Hope you solve the problem quickly.

**Comment by shermanfuhsd** [comment]
> 
> 
> Domain administrators must ensure that the toggle for "Access to additional services without individual control" is enabled in the Google Admin interface. See https://support.google.com/a/answer/7646040 for more information.


Just wanted to post because I've been looking to allow this for students and have pulling my hair out since this is basically the only thread I could find about this app.  Google's recent change to it's Over-18/Under-18 setup in Google Workspace has some fine print that any application that does not have the On/Off individual control will not be allowed for OU's marked as some users Under 18.  If you want Colab to work, the OU in Google that the account exists in must be listed as Over 18.  Apparently this and many other apps has schools marking all user OUs as over 18 because of this.  

As of today when I'm typing this, if you want Colab to work for students, the students OU must be marked as ALL over 18 years old.

**Comment by qkzk** [comment]
This problem is back again. Even if additionnal services are enabled it's not possible to open a colab notebook from a student account.

We solved it last month when it first occured by declaring our OA as over 18. 
Now, I can't open up (nor save) a colab notebook from a student account anymore.

It worked fine for 2 years and a lot of our lessons revolve around colab...

**Comment by cperry-goog** [comment]
@qkzk Do you know when you lost access again? And you're sure the age is over 18?

**Comment by qkzk** [comment]
@cperry-goog we lost access today or yesterday. A student contacted me 2 days ago and talked about his assignement. Today another one lost access again. I tried our test account and it didn't work.
We set up all OU as over 18... so yes I'm sure.

Here is what we see.

```
Désolé, vous n'avez pas accès à ce service. Veuillez contacter l'administrateur de votre organisation.

 - Billing terms - Privacy policy - Google Home
© 2021 Google LLC.
```

**Comment by kahwoo** [comment]
Suddenly can't access Google colab this morning
Checked that "Access to additional services without individual control" is on in admin console

Here's what users see:

We are sorry, but you do not have access to this service. Please log in to your Admin console to enable this service. Learn more

 - Billing terms - Privacy policy - Google Home
© 2021 Google LLC.

**Comment by cperry-goog** [comment]
Thanks for the reports; we're investigating right now.

**Comment by cperry-goog** [comment]
Thank you for writing us here, this saved us from a larger issue. Uncovered the bug, and we're rolling back now, you should see access reverted to normal in the next 30 minutes.

**Comment by karanbali** [comment]
I'm getting a similar error: "We are sorry, but you do not have access to this service. Please contact your Organization Administrator for access."

Colab suddenly stopped working about 4 hours ago & started showing the above error.  By when should we expect it to be back to normal?

**Comment by cperry-goog** [comment]
Rollback is a little slower than I predicted, but it's in progress now. Should be resolved any minute, but if you're having issues tomorrow hit me up again and we'll see if something else is broken.

**Comment by katlyn-edwards** [comment]
Rollback should be complete -- please feel free to comment if you're still experiencing issues.

**Comment by stockholmr** [comment]
We are getting the same message "You don't have access to this service. To request access, contact the administrator for your organisation’s Google services."

**Comment by thomasrmartin** [comment]
We're also seeing that issue for students who are in OUs set as under 18. Any update on this?

**Comment by cperry-goog** [comment]
#2264 is the main issue tracking <18 access; we're actively working on resolving, I'll announce on that thread when I have updates (will be soon)
