### ISSUE TITLE
java8 version not available 

### ISSUE THREAD

**Issue by referencelook** [googlecolab/colabtools#1256]
![java 8  not listing in jyupiter notebooks](https://user-images.githubusercontent.com/58660869/82175486-a4581e00-98f1-11ea-9665-74fbfeb327de.PNG)

**Comment by colaboratory-team** [comment]
There was an unintentional combination of Java 11 and Java 8 on colab VMs until recently (fixed in #915). Java 8 was intentionally dropped to reduce confusion.
If you need 8 specifically, you can re-install it using apt in notebook code.

**Comment by referencelook** [comment]
Pls provide me the steps to install java 8 in collab jyupiter notebook
Regards,
Pinky

**Comment by colaboratory-team** [comment]
Depending on whether you want a JRE or JDK some subset of:
`!apt-get install -y --no-install-recommends openjdk-8-{jre,jdk}-headless openjdk-8-jre`

**Comment by referencelook** [comment]
Thank you for your quick response.
Regards
Pinky

**Comment by referencelook** [comment]
Hi Googlecolab,

 After installing  jdk 8 it still shows java 11 . what should I do?
[image: image.png]

Regards,
Pinky

**Comment by colaboratory-team** [comment]
Use the update-alternatives command in your original screenshot.

**Comment by referencelook** [comment]
hi Googlecolab,

  Still it shows only java 11
[image: image.png]

Regards,
Pinky

**Comment by referencelook** [comment]
hi Googlecolab,
Its really disappointing , collab didnt support existing java 8 version
which we are using in all most all projects.

Regards,
Pinky

**Comment by Halfwayclover** [comment]
maybe too late but this should have helped you 
!apt-get install -y --no-install-recommends openjdk-8-{jre,jdk}-headless openjdk-8-jre
!update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
or you can pick any version you install (click on the folder icon on top in "Files" (with up arrow and .. next to it) and try to navigate here /usr/lib/jvm )

**Comment by Vamsi1810** [comment]
Yeah This works for installing java 8 version in colab
