### ISSUE TITLE
My keyboard is not working in google colab, I cant type or anything, please help.

### ISSUE THREAD

**Issue by Narenderm** [googlecolab/colabtools#1363]
Bug report for Colab: http://colab.research.google.com/.

For questions about colab usage, please use [stackoverflow](https://stackoverflow.com/questions/tagged/google-colaboratory/).

- Describe the current behavior:

- Describe the expected behavior:

- The web browser you are using (Chrome, Firefox, Safari, etc.):

- Link (not screenshot!) to a *minimal, public, self-contained* notebook that
  reproduces this issue (click the *Share* button, then *Get Shareable Link*):

**Comment by blois** [comment]
OS & Browser would help diagnose. If you are using desktop Chrome, can you try an incognito tab? Sometimes browser extensions get in the way.

**Comment by Narenderm** [comment]
Yes, its working fine in incognito window. So, do i always have to use it
in incognito? Can i uninstall some extensions from chrome to use it
properly?
Anyway, this was helpful, thank you so much!!

**Comment by blois** [comment]
If it is a problematic extension (certainly sounds like it), then disabling the extension should fix the issue.

You can try to narrow it down by incrementally disabling extensions or by incrementally enabling them in incognito. If you're able to narrow it down please do post your findings in case others run into the same issue.

**Comment by rajsingh010** [comment]
I was also facing this problem(in Edge) then I disabled google input tools extension and now it's working fine.

**Comment by blois** [comment]
Thanks for narrowing it down- this looks to be related to https://github.com/googlecolab/colabtools/issues/966.

**Comment by omarfarooq47** [comment]
I am seeing the same issue. The issue is still there in incognito, so the problem is not with an extension.

**Comment by cperry-goog** [comment]
@omarfarooq47 what browser and OS did you see this on? And is dark theme from within Colab, or from the browser or OS or an extension?

**Comment by omarfarooq47** [comment]
@cperry-goog The problem was not with the dark theme. I had selected settings>editor>editor key bindings>vim, which seemed to be causing the problem.
