### ISSUE TITLE
Colab pandas does not work

### ISSUE THREAD

**Issue by frabob2017** [googlecolab/colabtools#2591]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.
Pandas module in Google colab does not work to open excel spreadsheet in google drive today.  
pd.read_excel('*.xlsx') failed.   Used to work well.  show error. 

/usr/local/lib/python3.7/dist-packages/pandas/compat/_optional.py in import_optional_dependency(name, extra, errors, min_version)
    139                 return None
    140             elif errors == "raise":
--> 141                 raise ImportError(msg)
    142 
    143     return module

ImportError: Pandas requires version '3.0.0' or newer of 'openpyxl' (version '2.5.9' currently installed).
 
**What web browser you are using**
(Chrome, Firefox, Safari, etc.)
Chrome

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by craigcitro** [comment]
Thanks for the report -- we just updated pandas, which is causing the trouble.

*Immediate workaround:* `!pip install --upgrade openpyxl` and then hit the "restart runtime" button if it appears in the output.

**Comment by craigcitro** [comment]
Internal tracking: b/217463354

**Comment by cengizmehmet** [comment]
Hi @craigcitro ,
In case you would like to know, the same problem still exists.
I am looking forward to your permanent solution.
Cheers,

**Comment by Git5473** [comment]
Still an error @craigcitro 
ImportError: Pandas requires version '3.0.0' or newer of 'openpyxl' (version '2.5.9' currently installed).

**Comment by craigcitro** [comment]
To confirm, you're saying that you run `!pip install --upgrade openpyxl`, restart your runtime (ctrl-m . or `Runtime` -> `Restart runtime`), and still see errors?

If so, you'll need to share a public, minimal repro describing how to reproduce the problem. (The original report in this issue doesn't repro after those steps.)

**Comment by cengizmehmet** [comment]
Hi @craigcitro ,
I realised that I forgot the mention that `!pip install --upgrade openpyxl` and the restart thing are working. But as I used to work without installing any library, I would like to not do restart my runtime every time I opened my notebook.

**Comment by raulsolera** [comment]
` !pip install --upgrade openpyxl` solve the issue however I undestood this is just a temporarily workaround. Thank you.

**Comment by Git5473** [comment]
@craigcitro The error just now did not reappear and did not require a reboot
`!pip install --upgrade openpyxl`

**Comment by craigcitro** [comment]
Yep, we're all on the same page: I'm working on getting a fix submitted, but it'll take a few days before it's available. In the meantime, the workaround should keep you up and running.

(You'll only need a runtime restart if you've already imported pandas before running the `pip install`.)

**Comment by Paulo-Cerqueira** [comment]
Same issue for me...
Pandas requires version '3.0.0' or newer of 'openpyxl' (version '2.5.9' currently installed).

The proposed immediate workaround is not fully working (other issues are created).

Regards

**Comment by VishnuBhaarath** [comment]
> Thanks for the report -- we just updated pandas, which is causing the trouble.
> 
> _Immediate workaround:_ `!pip install --upgrade openpyxl` and then hit the "restart runtime" button if it appears in the output.

thank you it solves the issue

**Comment by himgoy** [comment]
@craigcitro Could you tell, what was the version of pandas before it was updated.

**Comment by craigcitro** [comment]
@himgoy Previously we were on 1.1.5.

**Comment by stephaniermiller** [comment]
@craigcitro , I attempted the "!pip install --update openpyxl" workaround and it work for a few hours, but now I am getting a new error: 
_AttributeError: module 'pandas' has no attribute 'load'_
screenshot:
![image](https://user-images.githubusercontent.com/65313518/152240193-af0c82dd-bd70-4eb1-b50b-f93e9390b70f.png)

I agree with @Paulo-Cerqueira that other pandas issues remain unresolved.

Let me know if it would be helpful for me to provide additional info. Can't wait to get me and my teams notebooks working again.

**Comment by craigcitro** [comment]
@stephaniermiller Thanks for the report -- we need a public, minimal, self-contained repro notebook demonstrating the issue. (In particular, pandas 1.1.5 also didn't have a top-level `load` function, so I suspect there's something else going on.)

**Comment by TJConnellyContingentMacro** [comment]
I had this issue and greatly appreciated your short-term workaround. These three lines of code are still working for me to retrieve an excel file of employment data from ADP's research site:

!pip install --upgrade openpyxl
import pandas as pd
pd.read_excel("https://adpemploymentreport.com/2022/January/NER/docs/ADP_NER_History_2022_01.xlsx")

(you can just open a new Colab notebook and run those in the first cell and it should work)

**Comment by shami2017** [comment]
@craigcitro 
Thanks, it is resolve now.

**Comment by Paulo-Cerqueira** [comment]
Hi @craigcitro ,

It is working for me now.
It seems that the file I was trying to open also had an issue...
So I can reinforce that the countermeasure proposed is working.
Thanks!

![image](https://user-images.githubusercontent.com/16608599/152348014-151b29c9-6b70-4824-9e22-962d1c3dd165.png)

**Comment by frabob2017** [comment]
!pip install --upgrade openpyxl
import pandas as pd

Same code, first time works, then 1 hour later, I log it back to colab. But it does not work. This is very wired.

**Comment by craigcitro** [comment]
@frabob2017 I suspect you got a new runtime when you came back an hour later; you'll need to re-run the pip install (and restart your runtime if the output suggests it).

Fix should land soon.

**Comment by craigcitro** [comment]
Fix for this should be live!

**Comment by raulsolera** [comment]
The solution works for me (no need for `!pip install --upgrade openpyxl`) Thank you!

**Comment by cengizmehmet** [comment]
Hi @craigcitro and colab team,
Thank you for solving the issue quickly. It works perfectly now.
Cheers

**Comment by VishnuBhaarath** [comment]
> The solution works for me (no need for `!pip install --upgrade openpyxl`) Thank you!

The issue was fixed

**Comment by cayhorstmann** [comment]
Today I ran into the same issue except with `xlrd`. The same workaround worked, but it's scary nonetheless when something as basic as pandas breaks for mysterious reasons.

**Comment by Dave86ch** [comment]
Hi everyone,
there is some related reason why I can't read a .xlsx after loaded in the files?

financial_data = pd.read_excel('/content/FBdataext.xlsx')

TypeError: __init__() got an unexpected keyword argument 'address'

it's strange because some weeks ago I didnt have this issue, I simply put my excel file in the files folder of colab (left side screen) and copied the path.

**Comment by pjmartel** [comment]
Hi everyone, 

the issue with reading excel files is not fixed. Now when I try to do:
```
df = pd.read_excel("/content/Grelha_Martel_Tool_OnlyMainData.xlsx", sheet_name=None)
```

I get the following error:

```
ValueError: Excel file format cannot be determined, you must specify an engine manually.
```

Adding the option `engine='openpyxl'` does not solve the issue, instead I get different error:

```
BadZipFile: File is not a zip file
```

The previous workaround `!pip install --upgrade openpyxl` isn't working anymore.

**Comment by Dave86ch** [comment]
> !pip install --upgrade openpyxl

Hello, there are news about this problem? Colab still can't open a excel I loaded

**Comment by baycelik** [comment]
> Thanks for the report -- we just updated pandas, which is causing the trouble.
> 
> _Immediate workaround:_ `!pip install --upgrade openpyxl` and then hit the "restart runtime" button if it appears in the output.

it works for me.
