### ISSUE TITLE
Can't connect Colab to a custom GCE VM after stopping and starting the instance

### ISSUE THREAD

**Issue by tomchify** [googlecolab/colabtools#2880]
**Describe the current behavior**
I have a long running Colab on a GCE VM. I noticed some kind of issue with CPU utilization slowly increasing to 100% from
https://console.cloud.google.com/compute/instances :
<img width="1196" alt="Screen Shot 2022-06-25 at 12 24 45 PM" src="https://user-images.githubusercontent.com/1762208/175787865-f5d91b85-07bf-48ce-a3ac-44ce68612cec.png">

I pressed "Stop", then "Start" on the VM instance.

Then I went back to the Colab and tried to connect to the custom GCE VM and got an error:
<img width="1389" alt="Screen Shot 2022-06-25 at 12 26 27 PM" src="https://user-images.githubusercontent.com/1762208/175787940-52cab720-e88e-4ea2-8d99-67ff36fb338a.png">

To try to fix this, I went to the "Deployment manager" and pressed the "Connect to VM with Colab" button, which had at some point worked to get access back, but unfortunately this time it still wasn't able to connect to the instance.

<img width="1170" alt="Screen Shot 2022-06-25 at 12 26 57 PM" src="https://user-images.githubusercontent.com/1762208/175787982-a81bbddd-2a75-4f0d-9986-7fa07746d912.png">

**Describe the expected behavior**
After stopping and starting an instance, Colab should be able to reconnect to the same GCE VM instance without error.

**What web browser you are using**
Chrome

Thanks for your help, or tips on how to manage memory issues with long running Colabs, or alternative environments or approaches to executing gpu tasks on Google's cloud ecosystem.

P.S. I've also experienced a Colab running connected to a custom GCE VM (say "colab-3-vm"), and while I watched the notebook crunch away and output stuff, the CPU utilization showed up as 0% in the Monitoring charts for the VM instance (for a long time). It seems like the Colab and custom GCE VM's aren't wiring up together somehow yet. Not sure if this is related.

**Comment by cperry-goog** [comment]
Closing this, please re-open if you encounter again. You should be able to reconnect if you Stop then Restart the instance.

**Comment by pranjal-zipteams** [comment]
@cperry-goog I'm currently experiencing this, my colab (on chrome) won't connect to a GCE VM which indeed shows as running on the GCP VM Instances dashboard

**Comment by ale-rls** [comment]
Im experiencing the same problem, any solutions?

**Comment by christiancgil** [comment]
The same problem for me, I lost several days

**Comment by itspranavk** [comment]
Same issue! Does anyone have a solution that worked?

**Comment by Merton** [comment]
The fix for me after experiencing this was (warning data in colab **_could be lost_** as the container gets removed):
1. SSH into the VM
2. `sudo systemctl status k_default` to see what was up with the service (k_default is the colab docker service)
3. Saw that it had failed to start, tried restarting it (`sudo systemctl restart k_default`) but didnt help.
4. Remove the docker container with `docker rm k_default`
5. Start the service again with `sudo systemctl start k_default`

I can now restart the instance just fine and haven't experienced any connections issues since

**Comment by alexleeds** [comment]
Just following up on this. For what it's worth, I ran into a similar issue using `Suspend`. Upon restarting the instance, I get the 

> VM requested does not exist

 message.

Inside the GUI, hitting `Reset` and restarting the instance did not solve the connection issue. Hitting `Stop` and then restarting the instance _did_ solve the connection issue.

**Comment by akhileshsiddhanti** [comment]
I am facing the same issue. Tried Stop/Start multiple times and still I get the same error "The requested VM does not exist".
Is there a fix for this?

**Comment by sjgosai** [comment]
I've run into this issue. I have a custom VM in us-west-1b that I have used for weeks (routinely turned it on and off without issue), but on Monday (Jun 5) I stopped being able to access it via Colab after starting it up. On Monday I kept getting an unhelpful "Can't Connect" error and today the error changed to "The VM requested does not exist. Check out our guide to set up GCE VMs in Colab". I have tried ssh-ing into the VM and using the Colab UI connection link that is provided upon login, but that doesn't work either.

**Comment by tomchify** [comment]
FYI for those stuck, I fixed all my Colab issues by switching to alternative services like vastai.com and tensordock.com where you have total control over the GPU and VM. Look into using nohup for long running processes on those platforms.

**Comment by Josuerinho** [comment]
Is there anyone assigned trying to solve this issue from Colab? I'm facing the same problem. Once stopped, can't connect again the VM to colab. Has anyone found any real solution to this problem? Thanks a lot, guys!

**Comment by hadikhamoud** [comment]
Going through the same issue. @Merton's suggestion works, but I lose the content directory files. Any help would be appreciated. Thanks!

**Comment by ctjlewis** [comment]
This is ridiculous. Comments on this regularly for the last year. Get it together.

**Comment by aviadshimoni** [comment]
@Merton solution isn't working for me. 
colab service is running but still getting Couldn't Connect. any idea how can I see further debug logs? TIA

**Comment by ctjlewis** [comment]
> @Merton solution isn't working for me. colab service is running but still getting Couldn't Connect. any idea how can I see further debug logs? TIA

Run the condensed code snippet I posted, what does the `sudo systemctl status k_default` output look like?

**Comment by ctjlewis** [comment]
> > @Merton solution isn't working for me. colab service is running but still getting Couldn't Connect. any idea how can I see further debug logs? TIA
> 
> Run the condensed code snippet I posted, what does the `sudo systemctl status k_default` output look like?
> 
> It's active and running, you verified the VM project ID and name? If you triple check all that the only thing you could do is open a ticket, i found that code snippet super reliable and had to come back a second time.

Update: I have come back a third time and this code snippet no longer works. Status now looks like:

```
lewis@colab-super-vm ~ $ sudo systemctl status k_default
× k_default.service - kernel default docker container
     Loaded: loaded (/etc/systemd/system/k_default.service; static)
     Active: failed (Result: exit-code) since Sat 2024-01-20 03:11:01 UTC; 8s ago
    Process: 1897 ExecStartPre=/usr/bin/docker-credential-gcr configure-docker (code=exited, status=0/SUCCESS)
    Process: 1903 ExecStartPre=/bin/bash -c mkdir -p /tmp/var-colab && touch /tmp/var-colab/mp (code=exited, s>
    Process: 1905 ExecStart=/usr/bin/docker run -u 0 --net br0 --ip 172.28.0.2 --name=k_default --cap-add SYS_>
   Main PID: 1905 (code=exited, status=125)
        CPU: 43ms

Jan 20 03:11:01 colab-super-vm systemd[1]: k_default.service: Scheduled restart job, restart counter is at 5.
Jan 20 03:11:01 colab-super-vm systemd[1]: Stopped kernel default docker container.
Jan 20 03:11:01 colab-super-vm systemd[1]: k_default.service: Start request repeated too quickly.
Jan 20 03:11:01 colab-super-vm systemd[1]: k_default.service: Failed with result 'exit-code'.
Jan 20 03:11:01 colab-super-vm systemd[1]: Failed to start kernel default docker container.
```

And the GUI now says "this instance does not exist." See [this SO issue](https://stackoverflow.com/questions/77147433/colab-vm-requested-does-not-exist-despite-status-claiming-it-is-running-and-ava).

Granted, this is an old VM, so maybe re-creating it from Marketplace will get us an instance that at least fails *recoverably* (and can be recovered by restarting the k_default service). Will update.

**Comment by ttehseen** [comment]
For me I can just not use any VMs even after I freshly create them. It just says: The VM requested does not exist. Take a look at our guide to set up GCE VMs in Colab.

**Comment by abhishekpatil32** [comment]
I was able to resolve this issue without losing the existing data by following these steps:

**1. SSH into the VM**

**2. Check the existing containers**: List all containers running on your VM to find the default one:
`sudo docker ps -a`

**3. Create a new container**: Start a new container (for example, named k_default1) to act as a replacement for the default one:
`sudo docker start k_default1`

**4. Copy data from the default container**: Copy the content from the default container (assuming it's named k_default) to a temporary location on your VM:
`sudo docker cp k_default:/content /tmp/data`

**5. Transfer data to the new container**: Copy the data from /tmp/data into your new container k_default1:
`sudo docker cp /tmp/data k_default1:/content`

**6. Stop the default container**: Once the data is copied, you can stop the default container to avoid conflicts:
`sudo docker stop k_default`

After completing these steps, the VM should function as expected with the new container.
