### ISSUE TITLE
Opening pickled files saved in Google Drive causes Colab notebook to hang

### ISSUE THREAD

**Issue by davidshumway** [googlecolab/colabtools#3136]
**Describe the current behavior**
Occasionally, opening pickled files saved in Google Drive causes the jupyter notebook to hang. The issue is sporadic. Sometimes the issue happens, other times it does not. Opening 10 pickled files, 1/10 may cause the loading process to hang (i.e., it's not always the first pickled file that causes the issue). The pickled files were saved at different times but were all saved from within the Colab environment and all saved to Google Drive. None of the files were saved when using GPU. The issue happens both when running with and without the GPU. The pickled files are typically less than 2MB. When the issue occurs, the RAM usage always spikes up to nearly 100% as depicted by the Colab RAM usage chart.

Example of code used to open pickled files:

```python
from google.colab import drive
import pickle
drive.mount('/content/gdrive')
%cd /content/gdrive/MyDrive/
pickle.load(open('test.pkl', 'rb'))
```

Interrupting the notebook usually does not work. Or if it does work, then after interrupting, the notebook is unusable where running a cell just results in the cell "loading" action to occur with no output.

In this case, the notebook is saved as a gist on Github. But the issue has also occurred when using a notebook that is saved in Google drive.

Occasionally, the cell will die with the following message:
```
ConnectionAbortedError: [Errno 103] Software caused connection abort
```
After which the kernel needs to be reloaded, otherwise the following message occurs:
```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-8817ba280272>", line 117, in <module>
    table(superv=True)
  File "<ipython-input-3-8817ba280272>", line 77, in table
    b4 = pickle.load(open('[file].pkl', 'rb'))
OSError: [Errno 107] Transport endpoint is not connected: '[file].pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 2040, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 319, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/IPython/core/ultratb.py", line 353, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.7/inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.7/inspect.py", line 1460, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.7/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.7/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.7/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.7/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

```

Output of the javascript console when the notebook has frozen:
```
initResin external_polymer_binary.js:194:269
Loading... external_polymer_binary.js:2725:55
Loading notebook. https://gist.github.com/[username]/[id]#[notebook title] external_polymer_binary.js:3479:416
Service workers are disabled SecurityError: The operation is insecure. 2 output_binary.js:149:314
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Partitioned cookie or storage access was provided to “https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Partitioned cookie or storage access was provided to “https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Partitioned cookie or storage access was provided to “https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Partitioned cookie or storage access was provided to “https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Partitioned cookie or storage access was provided to “https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Partitioned cookie or storage access was provided to “https://23eeyef71bm-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Connected to https://colab.research.google.com/tun/m/m-s-1i9j7zfypj8ds external_polymer_binary.js:6411:1111
LSP: Pyright language server 1.1.267 starting external_polymer_binary.js:6081:223
LSP: Server root directory: /datalab/web/pyright external_polymer_binary.js:6081:223
LSP: Starting service instance "<default>" external_polymer_binary.js:6081:223
LSP: Background analysis(1) root directory: /datalab/web/pyright external_polymer_binary.js:6081:223
LSP: Background analysis(1) started external_polymer_binary.js:6081:223
LSP: Un-registering request handler for 70be23cc-dcba-4b86-8684-c44b478d53e0 failed. external_polymer_binary.js:6081:223
LSP: stubPath typings is not a valid directory. external_polymer_binary.js:6081:223
result was "accepted" errorReason: external_polymer_binary.js:6822:69
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://v6r528x2kx-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Partitioned cookie or storage access was provided to “https://v6r528x2kx-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
LSP: Pyright language server 1.1.267 starting external_polymer_binary.js:6081:223
LSP: Server root directory: /datalab/web/pyright external_polymer_binary.js:6081:223
LSP: Starting service instance "<default>" external_polymer_binary.js:6081:223
LSP: Background analysis(1) root directory: /datalab/web/pyright external_polymer_binary.js:6081:223
LSP: Background analysis(1) started external_polymer_binary.js:6081:223
LSP: Un-registering request handler for 5ba07ed8-3852-468b-b6a7-3a10c0f17b16 failed. external_polymer_binary.js:6081:223
LSP: stubPath typings is not a valid directory. external_polymer_binary.js:6081:223
Some cookies are misusing the recommended “SameSite“ attribute 1055
Empty string passed to getElementById(). 15 external_polymer_binary.js:515:168
Empty string passed to getElementById(). 7 external_polymer_binary.js:515:168
Empty string passed to getElementById(). external_polymer_binary.js:515:168
Empty string passed to getElementById(). 2 external_polymer_binary.js:515:168
Empty string passed to getElementById(). 3 external_polymer_binary.js:515:168
Feature Policy: Skipping unsupported feature name “accelerometer”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “autoplay”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “gyroscope”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “magnetometer”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “serial”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “usb”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “clipboard-write”. external_polymer_binary.js:3912:330
Feature Policy: Skipping unsupported feature name “accelerometer”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “autoplay”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “gyroscope”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “magnetometer”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “serial”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “usb”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “clipboard-write”. external_polymer_binary.js:3913:413
Feature Policy: Skipping unsupported feature name “accelerometer”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “autoplay”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “gyroscope”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “magnetometer”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “serial”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “usb”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “xr-spatial-tracking”. external_polymer_binary.js:3914:337
Feature Policy: Skipping unsupported feature name “clipboard-write”. external_polymer_binary.js:3914:337
Content Security Policy: Ignoring “'report-sample'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/js/bg/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://support.google.com/inapp/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/tools/feedback/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/inproduct_help/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/support/content/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'report-sample'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/js/bg/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://support.google.com/inapp/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/tools/feedback/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/inproduct_help/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/support/content/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'report-sample'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/js/bg/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://support.google.com/inapp/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/tools/feedback/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/inproduct_help/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/support/content/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'report-sample'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/js/bg/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://support.google.com/inapp/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/tools/feedback/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/inproduct_help/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/support/content/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.google.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https://www.gstatic.com/recaptcha/” within script-src: ‘strict-dynamic’ specified
No output window available external_polymer_binary.js:3932:263
Using //@ to indicate sourceURL pragmas is deprecated. Use //# instead outputframe.html:169:14
Failed to register/update a ServiceWorker for scope ‘https://v6r528x2kx-496ff2e9c6d22116-0-colab.googleusercontent.com/’: Storage access is restricted in this context due to user settings or private browsing mode. outputframe.html:149:156
Service workers are disabled SecurityError: The operation is insecure. output_binary.js:149:314
Partitioned cookie or storage access was provided to “https://v6r528x2kx-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20221006-060055-RC01_479328028” because it is loaded in the third-party context and dynamic state partitioning is enabled.
Element.setCapture() is deprecated. Use Element.setPointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/setPointerCapture external_polymer_binary.js:521:144
Document.releaseCapture() is deprecated. Use Element.releasePointerCapture() instead. For more help https://developer.mozilla.org/docs/Web/API/Element/releasePointerCapture external_polymer_binary.js:523:102
Empty string passed to getElementById(). external_polymer_binary.js:515:168
Empty string passed to getElementById(). 4 external_polymer_binary.js:515:168
Empty string passed to getElementById(). external_polymer_binary.js:515:168
Empty string passed to getElementById(). 6 external_polymer_binary.js:515:168
Empty string passed to getElementById(). 7 external_polymer_binary.js:515:168

```

**Describe the expected behavior**

**What web browser you are using**
Tried in both Chrome and Firefox

**Additional context**

**Comment by davidshumway** [comment]
After restarting the kernel numerous times, setting the `buffering` parameter to 0 in the `open` method managed to fix the issue. Perhaps this was just by chance that it worked this time? i.e. `pickle.load(open('[file].pkl', 'rb', buffering=0))`

**Comment by davidshumway** [comment]
It just happened again. Apparently `buffering=0` is not a solution.

**Comment by davidshumway** [comment]
After some more trial and error with kernel restarts, this time this happened to work:

```
pickle.load(open('[...].pkl', 'rb'), encoding='bytes')
```

**Comment by davidshumway** [comment]
Nope. Just happened again regardless of `encoding='bytes'`

**Comment by davidshumway** [comment]
Just walked away from the computer and came back 40 minutes later to see the notebook still hung on this line (2MB pickle file):
```
pickle.load(open('/content/gdrive/MyDrive/[...].pkl', 'rb', buffering=0), encoding='bytes')
```

**Comment by davidshumway** [comment]
Any ideas ??

**Comment by davidshumway** [comment]
The pickled files were being loaded within a function, like so:
```python
def show():
  f1 = pickle.load(open('/content/gdrive/MyDrive/f1.pkl', 'rb', buffering=0), encoding='bytes'),
  f2 = pickle.load(open('/content/gdrive/MyDrive/f2.pkl', 'rb', buffering=0), encoding='bytes'),
  f3 = pickle.load(open('/content/gdrive/MyDrive/f3.pkl', 'rb', buffering=0), encoding='bytes'),
  f4 = pickle.load(open('/content/gdrive/MyDrive/f4.pkl', 'rb', buffering=0), encoding='bytes'),
  f5 = pickle.load(open('/content/gdrive/MyDrive/f5.pkl', 'rb', buffering=0), encoding='bytes'),
  f6 = pickle.load(open('/content/gdrive/MyDrive/f6.pkl'', 'rb', buffering=0), encoding='bytes')
  # run add'l code here
show()
show()
show()
```

Changing to the following happened to solve this issue, this time at least:
```python
files = [
  pickle.load(open('/content/gdrive/MyDrive/f1.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f2.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f3.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f4.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f5.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f6.pkl'', 'rb', buffering=0), encoding='bytes')
]
def show():
  global files
  f1 = files[0]
  f2 = files[1]
  f3 = files[2]
  f4 = files[3]
  f5 = files[4]
  f6 = files[5]
  # add'l code
show()
show()
show()
```

**Comment by davidshumway** [comment]
Nope, it happened again.

> files = [
  pickle.load(open('/content/gdrive/MyDrive/f1.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f2.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f3.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f4.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f5.pkl', 'rb', buffering=0), encoding='bytes'),
  pickle.load(open('/content/gdrive/MyDrive/f6.pkl'', 'rb', buffering=0), encoding='bytes')
]

**Comment by davidshumway** [comment]
Adding a 2-second sleep between unpickling each file also doesn't work. This loads files 0-4 but freezes on the fifth one:

```python
files = [
  '/content/gdrive/MyDrive/f1.pkl',
  '/content/gdrive/MyDrive/f2.pkl',
  '/content/gdrive/MyDrive/f3.pkl',
  '/content/gdrive/MyDrive/f4.pkl',
  '/content/gdrive/MyDrive/f5.pkl',
  '/content/gdrive/MyDrive/f6.pkl',
]
import time
i = 0
for f in files:
  files[i] = pickle.load(open(f, 'rb'))
  print(i)
  time.sleep(2)
  i += 1
```

**Comment by RyuuOujiXS** [comment]
You may be experiencing issues related to incompatible pickles. Were the pickles initially generated using a different version of pandas or python? If the pickles were made with the same version of packages and python, this isn't a concern.

**Comment by RyuuOujiXS** [comment]
Does the issue still occur if you copy all the pickles to the local file system first? I believe Colab runs off an Ubuntu VM so expect that file structure.

**Comment by davidshumway** [comment]
> You may be experiencing issues related to incompatible pickles. Were the pickles initially generated using a different version of pandas or python? If the pickles were made with the same version of packages and python, this isn't a concern.

They were all generated from within Colab within the last 2-3 weeks using default pandas and python from within Colab.

> Does the issue still occur if you copy all the pickles to the local file system first? I believe Colab runs off an Ubuntu VM so expect that file structure.

Good question. I can try this out the next time the issue occurs. It's happening once or twice per day lately, so I should be able to try it out shortly. I assume `/tmp` would suffice for the location?, e.g.

```bash
!cp *.pkl /tmp
```

**Comment by RyuuOujiXS** [comment]
> > You may be experiencing issues related to incompatible pickles. Were the pickles initially generated using a different version of pandas or python? If the pickles were made with the same version of packages and python, this isn't a concern.
> 
> They were all generated from within Colab within the last 2-3 weeks using default pandas and python from within Colab.
> 
> > Does the issue still occur if you copy all the pickles to the local file system first? I believe Colab runs off an Ubuntu VM so expect that file structure.
> 
> Good idea. I can try this out the next time the issue occurs. It's happening once or twice per day lately, so I should be able to try it out shortly. I assume `/tmp` would suffice for the location?, e.g.
> 
> ```shell
> !cp *.pkl /tmp
> ```


I think Colab prefers /content, the same directory sample_data is in

**Comment by davidshumway** [comment]
> I think Colab prefers /content, the same directory sample_data is in

So I tried copying the pickled files to /content and it still has the issue. In fact, however, this time the copy command rather than `pickle.load` is causing the RAM to go to 100% and the notebook to hang. So that's a step forward. Guess it's okay to close the issue on the pickle tracker.

But what else is there to try here then?

**Comment by davidshumway** [comment]
Following up to say that copying files to /tmp also doesn't resolve this. The issue is still there. This time the notebook is hung when copying the last of six files to /tmp, e.g.:

```python
!cp "/content/gdrive/MyDrive/ONR/1.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/ONR/2.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/ONR/3.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/ONR/4.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/ONR/5.pkl" /tmp #works
!cp "/content/gdrive/MyDrive/ONR/6.pkl" /tmp # notebook hangs
```

**Comment by davidshumway** [comment]
Nope. `--force` also doesn't resolve this. The issue is still there.

**Comment by davidshumway** [comment]
I've had this same issue previously in a different context (writing to a file). That issue is here: (https://github.com/googlecolab/colabtools/issues/2737). I believe that I closed that issue because it seemed resolve by simply rearranging some of the files writes.

**Comment by davidshumway** [comment]
This time the issue was resolved after moving to `/tmp/` before copying the files to `/tmp`:

```python
%cd /tmp
cp /content/gdrive/MyDrive/test/1.pkl /tmp
```

**Comment by davidshumway** [comment]
Nope. `%cd /tmp` also doesn't resolve this. The issue is still there.

**Comment by davidshumway** [comment]
Removing some unnecessary imports happened to fix the issue this time:


```python
from google.colab import drive
drive.mount('/content/gdrive')
%cd /content/gdrive/MyDrive/test/

''' Commented out this stuff...
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:.2f}'.format
np.set_printoptions(suppress=True)
pd.set_option('display.max_colwidth', 120)
import pickle
import warnings
warnings.filterwarnings('ignore')
'''

# Works this time ...
!cp {...}
pickle.load({...})
```

**Comment by RyuuOujiXS** [comment]
You're causing confusion. If your actual issue isn't to copy files across
the vm, don't say that resolved the issue.

**Comment by davidshumway** [comment]
> You're causing confusion. If your actual issue isn't to copy files across the vm, don't say that resolved the issue.

Okay, groucho. Anyone other devs on here willing to take a look at the issue?

The problem is intermittent. It comes and goes. When it comes, I try to resolve it in various ways. If you'd prefer that I didn't report back on what's working and not working, I can happily close the issue and walk away. I'm happy to find another service. Do you have a manager that I could talk to?

**Comment by RyuuOujiXS** [comment]
Go Karen somewhere else

**Comment by davidshumway** [comment]
Also I never said the issue was fixed.

**Comment by davidshumway** [comment]
Can someone else step in here? Please.

**Comment by cperry-goog** [comment]
@RyuuOujiXS please be respectful of other commenters. We do block users for negative behavior on here.

@davidshumway one of the eng is taking a look at this, no timeline as of now.

**Comment by davidshumway** [comment]
Thanks, @cperry-goog

**Comment by RyuuOujiXS** [comment]
> @RyuuOujiXS please be respectful of other commenters. We do block users for negative behavior on here.
> 
> @davidshumway one of the eng is taking a look at this, no timeline as of now.

You're right. I'll try harder.



> I've had this same issue previously in a different context (writing to a file). That issue is here: (#2737). I believe that I closed that issue because it seemed resolve by simply rearranging some of the files writes.

> This time the issue was resolved after moving to `/tmp/` before copying the files to `/tmp`:
> 
> ```python
> %cd /tmp
> cp /content/gdrive/MyDrive/test/1.pkl /tmp
> ```
> 
> I'll use this method and check back in if it stops working.

> Also I never said the issue was fixed.

So, back to your issue: I'm glad your separate issue was resolved. I'm glad your current issue was resolved. I'm sorry to hear your issue was only resolved, but not fixed. If I misunderstood something, please clarify. Also, please don't call me a "groucho". I find the term demeaning and disrespectful, especially seeing as I'm literally the only one who offered you any help.

**Comment by davidshumway** [comment]
> So, back to your issue: I'm glad your separate issue was resolved. I'm glad your current issue was resolved. I'm sorry to hear your issue was only resolved, but not fixed. If I misunderstood something, please clarify. Also, please don't call me a "groucho". I find the term demeaning and disrespectful, especially seeing as I'm literally the only one who offered you any help.

Actually, now that I think of it, the previous issue (https://github.com/googlecolab/colabtools/issues/2737) is the same as this one. And no, neither issue is resolved. I marked the last one as closed. But it is fundamentally the same issue as this one, and this one is not fixed.

> You're causing confusion. If your actual issue isn't to copy files across the vm, don't say that resolved the issue.

Would you prefer if I don't provide troubleshooting on my end? I'm trying to figure out why the issue is occurring to better help devs to correct the issue.

> If your actual issue isn't to copy files across the vm, don't say that resolved the issue.

Also, what are you talking about here? I don't understand what you mean.

My issue is that apparently copying files across the vm causes the vm to hang, become unresponsive, and only option left is restarting the kernel. Which is an utter waste of time when dealing with loading and processing files, etc.

When I say "resolved", I'm simply saying that I tried something and that appeared to work, at least momentarily. But when I say that, I also say this: "I'll start using [METHOD THAT SEEMS TO WORK] for now and check back in if it stops working." What's hard to understand about that? Perhaps you're not reading my messages in full?

Perhaps you could clarify what you mean by this statement: "If your actual issue isn't to copy files across the vm, don't say that resolved the issue."

**Comment by davidshumway** [comment]
And I'm sorry for a bit of name-calling calling you groucho. Your response seemed curt and cranky.

**Comment by cperry-goog** [comment]
Are you hitting our Drive limits? I just noticed you mentioning an extreme amount of data stored in Drive https://research.google.com/colaboratory/faq.html#drive-timeout

**Comment by davidshumway** [comment]
> Are you hitting our Drive limits? I just noticed you mentioning an extreme amount of data stored in Drive https://research.google.com/colaboratory/faq.html#drive-timeout

Yes that's probably the issue. Thanks for pointing out the faq note.

**Comment by justintimewatkins** [comment]
I don't know how much this would help anyone but when I was processing a lot of files which don't hit RAM limits on the colab instance I was running into this issue also where it was hanging on loading files, for some reason it was always the 57th one. The biggest thing which made it so I could continuously process without issue was putting a sufficient runtime delay between each file load that I was processing. Most of my files were about 27 MB each but I ran into issues whenever the seconds of processing per file went under 2 seconds per file. I had about a 2 second delay added to each one after. I still have less than 10,000 files in the subfolder I was working with also though too.
