### ISSUE TITLE
Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED using 0.1 drivers since 10/02/2023

### ISSUE THREAD

**Issue by henk717** [googlecolab/colabtools#3405]
**Describe the current behavior**
When running an older version of JAX, the TPU receives the following error:
Traceback (most recent call last):
  File "aiserver.py", line 10214, in <module>
    load_model(initial_load=True)
  File "aiserver.py", line 2806, in load_model
    tpu_mtj_backend.load_model(vars.custmodpth, hf_checkpoint=vars.model not in ("TPUMeshTransformerGPTJ", "TPUMeshTransformerGPTNeoX") and vars.use_colab_tpu, **vars.modelconfig)
  File "/content/KoboldAI-Client/tpu_mtj_backend.py", line 1194, in load_model
    devices = np.array(jax.devices()[:cores_per_replica]).reshape(mesh_shape)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 314, in devices
    return get_backend(backend).devices()
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 258, in get_backend
    return _get_backend_uncached(platform)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/lib/xla_bridge.py", line 248, in _get_backend_uncached
    raise RuntimeError(f"Requested backend {platform}, but it failed "
RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.106.231.74:8470. Error from gRPC: Deadline Exceeded. Details: 

This happens for all users of the notebook on Colab, while Kaggle is still working as intended.

**Describe the expected behavior**
Jax is correctly able to connect to the TPU and can then proceed with loading the user defined model. 

**What web browser you are using**
This issue does not depend on a browser, but for completeness I am using an up to date Microsoft Edge.

**Additional context**
Here is an example of an effected notebook:
```
import os
if not os.path.exists("/content/drive"):
  os.mkdir("/content/drive")
if not os.path.exists("/content/drive/MyDrive/"):
  os.mkdir("/content/drive/MyDrive/")

!wget https://koboldai.org/ckds -O - | bash /dev/stdin --model EleutherAI/gpt-neox-20b
```

The relevant backend code can be found here : https://github.com/KoboldAI/KoboldAI-Client/blob/main/tpu_mtj_backend.py
This also makes use of a heavily modified MTJ with the following relevant dependencies:
jax == 0.2.21
jaxlib >= 0.1.69, <= 0.3.7
git+https://github.com/VE-FORBRYDERNE/mesh-transformer-jax@ck

MTJ uses tpu_driver0.1_dev20210607

**Comment by mosmos6** [comment]
I'm encountering the same issue when loading GPT-J. It was working fine until 24 hours ago approximately.

**Comment by henk717** [comment]
> I'm encountering the same issue when loading GPT-J. It was working fine until 24 hours ago approximately.
Our code is based on MTJ which the original GPT-J runs on top off and happens prior to loading the model, both use the older V1 implementation of the model.
So its probable this effects all MTJ users.

**Comment by mosmos6** [comment]
Mine is trying to connect grpc://10.63.28.250:8470 and errors so it's pretty much everywhere. Furthermore, it's also taking unusually long to collect pathy and uvicorn, etc..

**Comment by henk717** [comment]
I have pinpointed the issue down to the driver version the projects use. It looks like the older ones are no longer working.
For example tpu_driver0.1_dev20210607 is being used in our project, when paired with the following code you get the error:
```
!pip install jax jaxlib 

import requests
import os
import jax

from jax.config import config

print("Connecting to your Colab instance's TPU", flush=True)
if os.environ.get('COLAB_TPU_ADDR', '') != '':
    tpu_address = os.environ['COLAB_TPU_ADDR']  # Colab
else:
    tpu_address = os.environ['TPU_NAME']  # Kaggle
tpu_address = tpu_address.replace("grpc://", "")
tpu_address_without_port = tpu_address.split(':', 1)[0]
url = f'http://{tpu_address_without_port}:8475/requestversion/tpu_driver0.1_dev20210607'
requests.post(url)
config.FLAGS.jax_xla_backend = "tpu_driver"
config.FLAGS.jax_backend_target = "grpc://" + tpu_address
print()

jax.devices()
```
I can't find a list of all available drivers, but collected 3 from bug reports and other colabs.

tpu_driver0.1_dev20210607 is used by us and produces the error, tpu_driver0.1-dev20211030 is newer and used by some examples where people recommend not to use the nightly, this also produces the error.

tpu_driver_20221011 is being used by some stable diffusion colabs and that one works in my example above. But unfortunately does not work with our MTJ notebook.

If someone knows a list of long term supported drivers I could test more of them and see if this fixes the issue for MTJ. Otherwise i'd like to politely request that the commonly used older drivers are restored in functionality. GPT-J and MTJ are still widely used but rely on older driver versions.

**Comment by mosmos6** [comment]
GPT-J doesn't work with tpu_driver_20221011 either.

**Comment by henk717** [comment]
GPT-J won't work with that indeed, but it does make a difference between connecting to the TPU and getting the deadline errors.
We will have to wait for the Google engineers to fix the 0.1 drivers we depend upon, for the time being Kaggle still works so if you have something urgent that can be done on Kaggle I recommend checking there until they have some time to fix it.

**Comment by mosmos6** [comment]
Thank you @henk717 I heavily use GPT-J everyday for work so I'll need it running from Monday morning. I hope this is a temporary issue.

**Comment by henk717** [comment]
I hope so to, but breaking the entire 0.1 driver ecosystem does not sound like the thing they did on purpose and won't be interested in fixing before this gets installed on things like Kaggle and Google Compute.

My theory is the TPUv2 firmware update that causes this either has been spread everywhere and the TPUv3 is unaffected, or they used Colab as a testing ground to see if people would run into issues and we are the first to notice because we rely on a dependency from the 2021 TPU era.

**Comment by mosmos6** [comment]
Is there a way to infer GPT-J from jupyter notebook on TPU machine of GCP?

**Comment by henk717** [comment]
Tagging @ultrons since he is the project manager for the TPU's. He may be able to get this to the right person. Thousands depend on MTJ for inference since it can be used to automatically load some huggingface pytorch models on the TPU. 

But especially since this is a failture to initialize the TPU at a very basic level. With the 0.1 driver resulting in a broken unresponsive TPU I expect this effects more colab users than the ones depending on MTJ. And if this same firmware bug spreads outside of colab more TPU customers could be effected on the entire google cloud.

**Comment by mosmos6** [comment]
I'm subscribing pro for TPU. If it stays uninitializable, it's no use..

**Comment by candymint23** [comment]
Can confirm this problem with the GPT models I use. I can't run them because of the same problem.

**Comment by metrizable** [comment]
@henk717 Thanks for reporting the issue and thanks for using Colab. I can confirm that specifying the 0.1dev does not work, but taking the default and specifying the 0.2 drivers does work. Tracking internally at b/269607171.

**Comment by somsomers** [comment]
> @henk717 Thanks for reporting the issue and thanks for using Colab. I can confirm that specifying the 0.1dev does not work, but taking the default and specifying the 0.2 drivers does work. Tracking internally at b/269607171.

You mean, full driver path would be:
```
colab_tpu_addr = os.environ['COLAB_TPU_ADDR'].split(':')[0]
url = f'http://{colab_tpu_addr}:8475/requestversion/tpu_driver0.2'
```
?

**Comment by henk717** [comment]
> > @henk717 Thanks for reporting the issue and thanks for using Colab. I can confirm that specifying the 0.1dev does not work, but taking the default and specifying the 0.2 drivers does work. Tracking internally at b/269607171.
> 
> You mean, full driver path would be:
> 
> ```
> colab_tpu_addr = os.environ['COLAB_TPU_ADDR'].split(':')[0]
> url = f'http://{colab_tpu_addr}:8475/requestversion/tpu_driver0.2'
> ```
> 
> ?

This is indeed correct, the 0.2 drivers and newer (including the ones that just use a 2022 version number without the other versioning) load fine. If your notebook is compatible with the newer drivers this can solve the issue for you, unfortunately a lot of the notebooks that directly call for a 0.1 driver will break when this is attempting because of incompatibilities.

**Comment by mosmos6** [comment]
@metrizable Thank you for taking care of this issue. Initializing the default and the 0.2 drivers are possible, but it causes crash when creating network of GPT-J, and probably its derivatives. So unfortunately I don't think these can be a temporary remedy.

**Comment by DamascusGit** [comment]
when will this be implemented on henk.tech/ckds? looking to use with colab kobold deployment script as currently have no way of converting my mesh transformer jax weights to HF.

**Comment by henk717** [comment]
> when will this be implemented on henk.tech/ckds? looking to use with colab kobold deployment script as currently have no way of converting my mesh transformer jax weights to HF.

You are commenting on a google issue not a Kobold issue. If it was as simple as changing versions I would have done so, but it is not the ckds script that decides this. Mesh Transformers Jax itself requests the broken driver and does so because it is not compatible with anything newer.

Since its a very low level dependency issue I am unable to resolve that myself as it requires deep knowledge of the TPU itself.

**Comment by wingk10** [comment]
Our operations team uses MTJ on a daily basis and hasn't been able to since the TPUs went down. Really hoping this gets resolved

**Comment by mosmos6** [comment]
@wingk10 I don't want to make this post lengthy but same here for me. Kaggle is affected and now the queue for TPU has over 70 users, which means we are likely to wait for 6 hours. We are even losing the alternatives.

**Comment by wingk10** [comment]
Yes, we're running into the same issue re: Kaggle. 64 users in the queue right now, and seems to have gotten worse suddenly over the past few days. Obviously, I can't do anything but post and go "hey, it's important to me too". I hope we hear more soon.

**Comment by mosmos6** [comment]
I decided to pay $10/h and tried to connect vertex AI to cloud TPU, but there was no available TPU in my bucket region. So, there are really no alternatives.

**Comment by candymint23** [comment]
Updates please?

**Comment by donkawechico** [comment]
I purchased Colab Pro+ last month and have barely been able to use it due to this issue 😭 Been 2 weeks since last update in this thread, would be great to get some news, even if it's just "still can't seem to get the danged thing working".

**Comment by somsomers** [comment]
It looks like either it's very difficult to fix or nobody cares.

**Comment by wingk10** [comment]
@metrizable Are there any updates on this? A lot of people rely on this setup of TPUs working for work and it's been some time since we heard anything.

**Comment by henk717** [comment]
In my own community its also thousands of people wanting to use the TPU's for inference again.
I am personally in the same boat as all the other Pro users here where the only reason I had pro is that it is an affordable high ram solution. For the GPU side I have different alternatives.

**Comment by mosmos6** [comment]
At least at this moment, the issue has been removed and now it's working for GPT-J. Good News.

**Comment by donkawechico** [comment]
Same here! Seems to be working for me.

**Comment by cperry-goog** [comment]
Glad it's resolved. For reference, we have no ability to get the older 0.1 TPU drivers up and running again. The outdated drivers were removed from a recent build upstream we haven't found any way to get those back in.

You'll need to upgrade to more recent drivers. Sorry.

**Comment by henk717** [comment]
@cperry-goog Our dependencies did not change, to my knowledge it is not literally using 0.1 drivers but it does initialize again when 0.1 is requested and operates in a compatible mode. Please keep this functional now that it works again. MTJ isn't actively maintained upstream but thousands depend on the fix that was pushed today.

I assume one of the TPU engineers managed to get it running again in the correct backwards compatible mode even if it is not running a real 0.1 driver. It would help if that part is marked as important for the ecosystem so it does not get broken again in the next updates.

**Comment by DamascusGit** [comment]
seems to be breaking again...

**Comment by AVKosterin** [comment]
> seems to be breaking again...

I see the problem too...

**Comment by mosmos6** [comment]
Yes, it's happening again. (Yesterday JAX related bug occurred in a couple of different forms. I thought it was because of the upgrade to Python3.9 from last week, but it wasn't. That issue was resolved by itself in a few hours.)

**Comment by henk717** [comment]
We also had a handful every week but those were always a thing and could be resolved by getting a new notebook. So when people report it normally they could get back in. But since last night its constant.

**Comment by mosmos6** [comment]
At this moment, none of 0.1, 0.2, nightly nor default driver can be initialized so the magnitude is higher.

**Comment by mosmos6** [comment]
I know this post is about colab, but let me add that I confirmed kaggle causes the same TPU initialization error this time. So there's no alternative now.

**Comment by candymint23** [comment]
> At this moment, none of 0.1, 0.2, nightly nor default driver can be initialized so the magnitude is higher than last time.

So apparently not just 0.1 driver issue, because when they said we cannot access 0.1 anymore, it still worked after their suppsoed changes several weeks ago.

**Comment by mosmos6** [comment]
@candymint23 By 4 hours ago, nightly and other drivers worked but 0.1. Apparently they are fixing the issue from other drivers.

**Comment by Borrowdale** [comment]
how long do these outages normal last?

**Comment by henk717** [comment]
Last time it was weeks, alao keep in mind when testing that incorrect drivers can hang. You need an empty colab session per driver attempt for reliable results. So far I only had the issue on 0.1.

Alao been looking at potential alternative frameworks such as pytorch xla with no success (Even 2.7B models didn't fit but its possible I did something wrong there). On those frameworks it does initialize the TPU fine, so its specifically Jax 0.1

**Comment by Borrowdale** [comment]
so i take it this is effecting everyone, its not something only a hand full of use are missing or doing wrong?

**Comment by henk717** [comment]
It is effecting anyone using MTJ or code relying on the older TPU Jax drivers. From what I saw Jax related projects older than one year old. So that is GPT-J, KoboldAI, and others who rely on MTJ but also projects beyond that I have no knowledge off.

Unfortunetly MTJ can't run properly on the newer driver so we are stuck on that front.

**Comment by Borrowdale** [comment]
i have no idea how this stuff works but is there a way to "ping" the driver(?) to see if its up/running/whatever the equivalent is so we can track when it back up or is there usually an announcement?

again, i have no idea what i'm talking about i'd just pulling this out of the voice assuming it works something like a server with no basis to do so lol 

sorry if i come across as a house brick.

**Comment by mosmos6** [comment]
A new symptom appeared. Though I need to use  jaxlib 0.1.68,  it requires  0.1.74.

1. 0.1.68 had no problem until yesterday under the same conditions.
2. The same issue appeared two days ago, and that time it disappeared in a few hours.
3. In Kaggle, 0.1.68 suddenly became unable to be installed on Python3.7 two days ago.

> On those frameworks it does initialize the TPU fine, so its specifically Jax 0.1

I'm guessing this whole situation is arising from a recent change in JAX. (Just guessing)


![Screenshot 2023-03-15 100838](https://user-images.githubusercontent.com/93764745/225247709-a54af190-093a-47a1-9e4d-538c98a7497d.jpg)

**Comment by mosmos6** [comment]
At this moment, TPU_driver0.1 can be initialized on colab (but not kaggle) but it can't create network.

**Comment by adamaxis** [comment]
Would be nice to hear if anyone is working on this, as a lot of people are experiencing issues.

**Comment by Borrowdale** [comment]
who would we contact to even find that out?  :(
think this is one of those things we have to assume someone is already aware of and working on.

**Comment by SirRizzalot** [comment]
is it appropriate to @ metrizable, it seems like he got it to the right people last time.

**Comment by Borrowdale** [comment]
that's good to know, hopefully they can do the same this time.

**Comment by SirRizzalot** [comment]
problem still exists as of now.

**Comment by candymint23** [comment]
Any updates please from Google?

**Comment by SirRizzalot** [comment]
> Any updates please from Google?

@metrizable can you get this to the right people? I'm fairly new here and the contributing guidelines didn't mention to not @ contributors. It seems like a lot of people are re-experiencing this issue, maybe you guys can look into it again.

**Comment by sarabconsulting** [comment]
Experiencing the same issue still. 

RuntimeError: Deadline exceeded: Failed to connect to remote server at address: grpc://10.89.22.138:8470. Error from gRPC: Deadline Exceeded.

**Comment by metrizable** [comment]
As cperry-goog mentioned in [#issuecomment-1451048147](https://github.com/googlecolab/colabtools/issues/3405#issuecomment-1451048147), the outdated drivers were removed from a build upstream and we haven't found a way to get those back in.

Although I know this doesn't solve the OP's use case (and I'm really just confirming what others have posted above) the TPU can be initialized with the 0.2 drivers or newer using the most recent `jax` (0.3.5) that's still compatible with TPU on Colab:

![W2d2nJQtkayCYNV](https://user-images.githubusercontent.com/65414824/225966149-8cfa8529-2aaa-4632-bcfa-bed090afa00a.png)

**Comment by henk717** [comment]
> Although I know this doesn't solve the OP's use case (and I'm really just confirming what others have posted above) the TPU can be initialized with the 0.2 drivers or newer using the most recent `jax` (0.3.5) that's still compatible with TPU on Colab:

@metrizable As mentioned before to @cperry-goog we had gotten the same answer from cperry two weeks ago on the same day it began working again. It is currently unsure why that was since it worked 3 hours prior to his response, and it also introduced a new warning in the code when it happened. So the functionality has been restored before possibly with a compatibility mode.

The people in this topic are primarily users of Mesh Transformers Jax which has been abandoned by its maintainer (And unfortunately ve-forbryderne has stopped showing signs of life so his fork is also completely unmaintained. Other than the original author he is the only one I know who is familiar with this type of work).

So all downstream projects are having a dependency level issue because driver compatibility was not maintained, MTJ at its time could not run on the newer Jax versions because of even more backwards compatibility issues that have never been addressed.

We aren't asking for a restoration of the real 0.1 driver, but we are asking for a solution for these older dependencies that have no modern alternatives. Such as a compatibility mode inside the newer 0.2 driver that can initialize when 0.1 is requested, and then runs in a form compatible with older code which seemingly existed the past two weeks unless the 0.1 drivers were put back for a brief amount of time.

If that is not possible it kills an entire ecosystem unless MTJ can be restored in functionality. For users of GPT-J alternatives exist outside of the TPU ecosystem. They can for example run the Huggingface port of GPT-J on a GPU. But what made MTJ unique was that various model formats have been ported to it with very high performance (This is on VE-Forbryderne's fork). This for example allowed up to GPT-NeoX 20B to run on a single colab TPUv2-8 with generation times of around 10 seconds. If I try the same use case on for example Pytorch Xla, I now can only run up to 2.7B and generation times are longer than one minute making it completely inferior to the GPU space in every way and useless for our users.

I also tried Tensorflow, but Tensorflow doesn't have the smooth model compatibility that MTJ had received over the years. With models needing a lot of ram to load (More than could be done on the free resources, or even paid resources) and often loaded with errors.

That means that for our use case if MTJ can not be restored in functionality trough a fix of the driver or trough a fix in the fork the only feasible option is abandoning the TPU entirely. TPU coders are very hard for open source projects to attract, so we can not find a new maintainer for the fork that is used by thousands of users.

**Comment by Borrowdale** [comment]
So if I've understood correctly (which i admit is unlikely), the TPU versions still runs but i have to somehow select 0.2 Driver?
How do I do that from the COlabKolold TPU run page? (or anywhere else it needs to be done from)  
Sorry again if i come across as ignorant, i am still learning the ropes.

**Comment by mosmos6** [comment]
@henk717 As I think GPT-J and MTJ are essentially similar, I found this inference code though I don't know the author.
https://colab.research.google.com/drive/13R8MJEDTwinEmUJMLqydKOIcAvWiBIlT#scrollTo=vaWUMv9RJO9T
Currently the weights are removed so it doesn't run, but it's using TPU_driver_nightly. Does this mean there is a way to utilize nightly?

**Comment by henk717** [comment]
Nightly is less desirable than any other newer driver since its always the newest one. It will be broken, back then nightly as a 0.1 driver.

**Comment by henk717** [comment]
@mosmos6 I will also give you a bit of a recap so you can understand why I need the driver to be fixed, but why for you some alternatives might exist.

Mesh Transformers Jax (MTJ) was the framework used to create GPT-J, so GPT-J in its original form runs on top of MTJ. It has been ported to other platforms, so you can also run it on a GPU using Huggingface Transformers for example. And that is how our own community runs GPT-J based models on colab now with a more limited context.

For us the issue is an issue in RAM. The affordable colab GPU's for our AI hobby have 16GB of VRAM, while the TPU has 64GB of RAM. So while GPT-J-6B is possible to run on a GPU, we can not fit as much context as the TPU version could.

In the past year VE-Forbryderne ported various formats, so his version of MTJ can run GPT-J, but also XGLM, OPT and even NeoX based models. And not just that, it can load those models using pytorch files without requiring conversion. This allowed us AI hobbyists to use models up to 20B very affordably on Google Colab which was why the TPU was so desirable for us. $10 a month (or limited free usage) is much better than having to pay $1 per hour on GPU rentals which is not affordable for open source hobbyists who wish to use the models.

If all you want is GPT-J-6B inference I suggest you switch your usage to Huggingface since you will be able to enjoy much better more reliable support on Colab and beyond for the same price. Its when you want the higher model sizes or training that the TPU becomes necessary. And the only platform that has that kind of cost effectiveness is Colab combined with a modified MTJ.

**Comment by mosmos6** [comment]
@henk717 Thank you for recapping. Sorry, I didn't know MTJ means Mesh Transformers Jax. Then it's exactly GPT-J.
My GPT-J model has been heavily finetuned over the past almost 2 years for a research project and it's the only one. 
I assume MTJ crashes on 0.2 because of JAX compatibility, and our JAX version needed to stay outdated due to xmap.
It'll be complex but I think it's possible to find an optimal versions of all the dependencies?

**Comment by henk717** [comment]
@mosmos6 In your specific use case its worth checking if conversion scripts like https://github.com/VE-FORBRYDERNE/mesh-transformer-jax/blob/all/to_hf_weights.py are still functional (For example with CPU dependencies) so that you can get your model out of this platform to futureproof your model.

If you are unable to you are stuck with the rest of the thousands of users that have no substitute for MTJ.

**Comment by mosmos6** [comment]
@henk717 Thank you for suggestion. I've been persistent with TPU because I think running on TPU or GPU makes significant differences in output quality for some reason, but I'll give it a try.
I upgraded my subscription to pro+ to try out all the possible combinations of dependencies. Some people claimed they had to downgrade JAX from 0.4 to 0.3.25 for TPU compatibility over the past few days.
What I'm saying is what's your plan? If 0.1 is entirely removed, at least GPT-J on TPU and its derivatives are technically left dead. We must find a way. When the issue was temporarily "resolved" a few weeks ago, my GPT-J said it's temporary and the issue won't be fixed. It was true. I and my GPT-J model were in the middle of a work to do. Probably many other folks here are the same.

**Comment by SirRizzalot** [comment]
3/20/2023 Connection error still persists.

**Comment by SirRizzalot** [comment]
3/22/2023 Connection error still persists.

**Comment by mosmos6** [comment]
Hello @metrizable @cperry-goog 

This issue has started where GPT-J and its derivatives could not be connected to TPU_driver0.1 anymore.

> You'll need to upgrade to more recent drivers. Sorry.

Hence, I updated my code so that it runs on JAX 0.3.5, which is compatible to TPU_driver0.2. 
Indeed my code is already running well on my V3-8 (v2-alpha) VM and I'm inferring with it on my screen beside this window.

However, the very same code errors at a particular point on colab so I would like you to take a look.
This is a miniature code based on [#6962](https://github.com/google/jax/issues/6962)  back in 2021.
Obviously I found an answer to this original question as it's already running on my TPU VM, but colab is having another issue.

```
import jax
import haiku as hk
import jax.numpy as jnp
import numpy as np
import time


class TransformerLayerShard(hk.Module):
    def __init__(self):
        super().__init__()
        self.dense_proj = hk.Linear(2048)
        self.dense_proj_o = hk.Linear(4096)

    def ff(self, x):
        dense_proj = self.dense_proj(x)
        dense_proj = jax.nn.gelu(dense_proj)
        return self.dense_proj_o(dense_proj)

    def __call__(self, x, attn_bias):
        dense_out = self.ff(x)

        return dense_out


mesh_shape = (1, 8)
devices = np.array(jax.devices()).reshape(mesh_shape)

with jax.experimental.maps.mesh(devices, ('dp', 'mp')):
    def init_old(key, x):
        def init_old_fn(x):
            return TransformerLayerShard()(x, 0)

        param_init_fn = hk.transform(hk.experimental.optimize_rng_use(init_old_fn)).init
        params = param_init_fn(key, x)
        return params

    init_xmap = jax.experimental.maps.xmap(fun=init_old,
                                            in_axes=(["shard", ...],
                                                     ["batch", ...]),
                                            out_axes=["shard", ...],
                                            axis_resources={'shard': 'mp', 'batch': 'dp'})

    key = hk.PRNGSequence(42)

    x = jax.random.uniform(next(key), (1, 1024, 2048))  # batch, len
    params = init_xmap(jnp.array(key.take(8)), x)

    def bwd_old(state, x):
        def bwd_old_fn(x):
            return jnp.sum(TransformerLayerShard()(x, 0))

        train_loss_fn = hk.without_apply_rng(hk.transform(bwd_old_fn)).apply
        val_grad_fn = jax.value_and_grad(train_loss_fn, has_aux=False)

        loss, grad = val_grad_fn(state, x)

        return grad

      
    run_xmap = jax.experimental.maps.xmap(fun=bwd_old,
                                          in_axes=(["shard", ...],
                                                     ["batch", ...]),
                                            out_axes=(["shard", "batch", ...], ["batch", ...]),
                                            axis_resources={'shard': 'mp', 'batch': 'dp'})

    run_xmap(params, x)


```

Before it runs down to the out_axes, code gets stuck at line 46, which is
`params = init_xmap(jnp.array(key.take(8)), x)`
 I waited for 1h but it didn't progress.

![Screenshot 2023-03-30 121032](https://user-images.githubusercontent.com/93764745/228873516-f4d66f22-d4db-4e3e-afd9-ea9d0bfe4ab2.jpg)

It seems to be a wrapper part of xmap. On TPU VM, this process finishes within a minute.
As it doesn't even show an error message, I have no clue about the problem.

I also tried pjit but it erros as
`RuntimeError: UNIMPLEMENTED: Only 1 computation per replica supported, 8 requested.`
Again, the pjit itself runs well on TPU VM so it's unique to colab. However, pjit has low priority compared to this xmap issue, for now.

As advised, I updated my code for the newer JAX and TPU_driver, which perfectly runs on TPU VM, but it gets stuck on colab.
Considering the accessibility to TPU VM, availability on colab is highly important.
Thank you for your attention.

**Comment by henk717** [comment]
AttributeError: module 'jax' has no attribute 'Array' is a new error related to chex doing a breaking change, I fixed this by pinning a suitable version in our requirements files.

Now the error is back to the one reported in this issue tracker.

**Comment by mosmos6** [comment]
Hello @metrizable @cperry-goog 

I upgraded my model even further to JAX 0.3.25 and I encountered this error on colab.

```
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in backends()
    332       try:
--> 333         backend = _init_backend(platform)
    334         _backends[platform] = backend

7 frames
[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in _init_backend(platform)
    384   logger.debug("Initializing backend '%s'", platform)
--> 385   backend = factory()
    386   # TODO(skye): consider raising more descriptive errors directly from backend

[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in tpu_client_timer_callback(timer_secs)
    190   try:
--> 191     client = xla_client.make_tpu_client()
    192   finally:

[/usr/local/lib/python3.9/dist-packages/jaxlib/xla_client.py](https://localhost:8080/#) in make_tpu_client()
    121         f'got {max_inflight_computations}') from e
--> 122   return _xla.get_tpu_client(
    123       max_inflight_computations=max_inflight_computations)

XlaRuntimeError: NOT_FOUND: No ba16c7433 device found.

During handling of the above exception, another exception occurred:

RuntimeError                              Traceback (most recent call last)
[<ipython-input-7-ff27931a0eed>](https://localhost:8080/#) in <cell line: 30>()
     28 params["optimizer"] = optax.scale(0)
     29 
---> 30 mesh_shape = (jax.device_count() // cores_per_replica, cores_per_replica)
     31 devices = np.array(jax.devices()).reshape(mesh_shape)
     32 

[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in device_count(backend)
    450 
    451   """
--> 452   return int(get_backend(backend).device_count())
    453 
    454 

[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in get_backend(platform)
    423 @lru_cache(maxsize=None)  # don't use util.memoize because there is no X64 dependence.
    424 def get_backend(platform=None):
--> 425   return _get_backend_uncached(platform)
    426 
    427 

[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in _get_backend_uncached(platform)
    407               or None)
    408 
--> 409   bs = backends()
    410   if platform is not None:
    411     platform = canonicalize_platform(platform)

[/usr/local/lib/python3.9/dist-packages/jax/_src/lib/xla_bridge.py](https://localhost:8080/#) in backends()
    348           if config.jax_platforms:
    349             err_msg += " (set JAX_PLATFORMS='' to automatically choose an available backend)"
--> 350             raise RuntimeError(err_msg)
    351           else:
    352             _backends_errors[platform] = str(err)

RuntimeError: Unable to initialize backend 'tpu': NOT_FOUND: No ba16c7433 device found. (set JAX_PLATFORMS='' to automatically choose an available backend)

```

Notes;

1. The very same code worked on TPU VM V3-8 (v2 alpha).
2. However, this VM started erroring when I loaded the model after I exited once, which is the same as this [#13260](https://github.com/google/jax/issues/13260).
3. The error of 2 looks similar to this error on colab. (I see Skye's TODO in the error log)
4. I tried both TPU_driver0.2 and _nightly but the symptoms were the same.

Thank you.

**Comment by henk717** [comment]
@mosmos6 Can you share your changes?

**Comment by mosmos6** [comment]
@henk717 ofc. Give me some minutes. Now I'm on my way to set up a repository as changes happened in multiple files. My test code needs clean up after one month experiments.

**Comment by henk717** [comment]
For us the challenge will be getting this one running : https://github.com/VE-FORBRYDERNE/mesh-transformer-jax/tree/ck it is a heavily modified version that has a lot more additions and enhancements but the developer went missing.

**Comment by mosmos6** [comment]
@somsomers Yes. Please let me clean up the mess before sharing.

**Comment by somsomers** [comment]
> @somsomers Yes. Please let me clean up the mess before sharing.

Thank you.

**Comment by mosmos6** [comment]
Hello,

First of all, I must apologize. This works only on high memory TPU runtime so you'll need pro or pro+ subscription of colab....
However, I modified the discussed model (GPT-J for me) so that it runs with TPU_driver0.2 on colab. 
Because it is not exactly linked to colab, I posted it here. 
(https://github.com/kingoflolz/mesh-transformer-jax/issues/256#issuecomment-1507188297)

I believe this can be deployed to other derivatives. 

@henk717 @somsomers

**Comment by mosmos6** [comment]
@henk717 

I fixed your AI. She's waiting for you to pick up in the garage. (https://github.com/mosmos6/Large-MTJ)

Same as my GPT-J, it's adapted to JAX 0.3.25 so it runs on colab with TPU_driver0.2. Basically this should be now immunized to JAX upgrading except breaking changes. Sorry for the dorky name, I didn't know her name.
The changes were small but many. I modified
`requirements.txt` (kept the original one as _original)
`slim_model.py`
`mesh_transformer/train_actor.py`
`device_sample.py`
`device_serve.py`
`device_train.py`
`mesh_transformer/transformer_shard.py`
`mesh_transformer/checkpoint.py`
The new colab demo is `Large_MTJ_inference_on_TPU_driver0_2.ipynb` (kept the original one as _original)
The rests remain the same.

I tested this only with my slim weights for GPT-J. If you run into an error with other types of weights, please post an issue.

Important notes;

1. Sorry, you'll need pro or pro+ subscription of colab because it requires high memory TPU runtime. `read_ckpt_lowmem` hangs forever when to infer with the model in the current colab environment. I had to revive `read_ckpt`. However this loads the model 10 times faster than low memory version. It quit showing total parameters for some reason too, but I don't think it matters.

2. I have not checked it for finetuning on TPU VM yet. This can cause errors during a process. I'm planning to cover it next month. Until then, possibly you must add further modifications to xmap by yourself or downgrade to jax 0.2.18 or 0.2.20.

3. Please let me know if you don't know how to use the new colab demo.


Enjoy

![Screenshot 2023-04-19 120424](https://user-images.githubusercontent.com/93764745/233037552-ff5c8188-d15e-4a3c-be88-e71fc501a486.jpg)

**Comment by mosmos6** [comment]
@henk717 

As I wrote, you can’t use `read_ckpt_lowmem ` anymore on colab.

**Comment by mosmos6** [comment]
Due to the python upgrade of colab (3.9 -> 3.10), I further modified two of my modified mtj models, and requirements.txt and util.py of each are updated.
Now these models can adapt to the later versions of optax than 0.0.9. They are immune to JAX upgrades and optax upgrades.

**Comment by dbubbins87** [comment]
So I'm not sure what happened, but it started working for a week, but just when I tried to use it tonight, I got the error again.

**Comment by sagelywizard** [comment]
This issue is obsolete because the TPU runtimes are deprecated and were removed.
