### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by ioritree** [googlecolab/colabtools#3441]
Hello, I am a user of colab pro+.(Chrome)
I have been experiencing the problem of "OSError: [Errno 107] Transport endpoint is not connected" in the process of training the model every day for a while, and I encounter it almost once a day, how to solve it?

And during this period, the training is still going on but no new model progress is generated, and the calculation units are continuously deducted, and if you don't pay attention, the whole day's calculation units are deducted.

[![Watch the video](https://images4.imagebam.com/8b/ca/16/MEJD8J9_o.jpg)](https://streamable.com/e5hn6k)
**upload video(click pic to watch video)**

**Start every day after the reset, training will appear after ten hours of this problem
I'm going crazy, epochs need at least take 3~4 hours !!**

**This has been happening every day since 2023/2/17 when colab updated something
The picture shows 8x% of the training progress, which took 3 hours, (at least 3 hours of training time per day was evaporated)**

mount method
from google.colab import drive
drive.mount('/content/drive')

**Comment by CathySunshine** [comment]
I had the same issue. I tried several ways to report this issue but have not received a reply.

**Comment by ioritree** [comment]
> I had the same issue. I tried several ways to report this issue but have not received a reply.

Start every day after the reset, training will appear after ten hours of this problem

**Comment by anthonyromyn** [comment]
looks like I'm getting the same problem

**Comment by yanavdsande** [comment]
I have the same problem - my units are deducted but the training was too short to be useful. I have saved my checkpoints and started training from there but my units are still gone.. @CathySunshine have you had a reply yet?

**Comment by ioritree** [comment]
> I have the same problem - my units are deducted but the training was too short to be useful. I have saved my checkpoints and started training from there but my units are still gone.. @CathySunshine have you had a reply yet?

no reply any :(

**Comment by anthonyromyn** [comment]
Small update on my end: looks to happen to me after only 4.5 hours. Looking into it more today

**Comment by CathySunshine** [comment]
> I have the same problem - my units are deducted but the training was too short to be useful. I have saved my checkpoints and started training from there but my units are still gone.. @CathySunshine have you had a reply yet?

Yes. seems to be the consequence of the mounted drive getting disconnected [https://github.com/googlecolab/colabtools/issues/3451#issuecomment-1453969719](url)
However, they are still investigating the disconnecting mounted drive issue

**Comment by ioritree** [comment]
> > I have the same problem - my units are deducted but the training was too short to be useful. I have saved my checkpoints and started training from there but my units are still gone.. @CathySunshine have you had a reply yet?
> 
> Yes. seems to be the consequence of the mounted drive getting disconnected [#3451](https://github.com/googlecolab/colabtools/issues/3451) However, they are still investigating the disconnecting mounted drive issue

At least it sounds like good news, I hope they can fix it as soon as possible

**Comment by LeapGamer** [comment]
I'm getting the same error in training, but colab runtime is still connected. My epochs take ~4hours, and I get this error when trying to save the data for the 3rd epoch during the run at the 12th hour:

`FailedPreconditionError: ...drive_path... Transport endpoint is not connected`

**Comment by ranjitkathiriya** [comment]
looks like I'm getting the same problem

**Comment by panyan7** [comment]
I'm getting the same problem. Waiting for a solution.

**Comment by Great-Bucket** [comment]
To test this problem more thoroughly, I wrote the a very simple script that makes a calculation with the GPU and then posts a 'dummy_file' to my Google Drive every 10 minutes. Though I expected it to run for 24 hours, the dummy files were only written for 9.7hrs. The final error message was 'Transport endpoint is not connected'. 

More details:
#3562

**Comment by dcloveUIUC** [comment]
Getting this same issue - any updates?

**Comment by NathanMoura** [comment]
Same problem. Waiting for a solution

**Comment by noirmist** [comment]
Same Problem. Any updates?

**Comment by Amosharid** [comment]
Same problem. Any updates?

**Comment by aigagror** [comment]
Same problem. Any updates?

**Comment by TeoCavi** [comment]
Same problem, Any updates?

**Comment by MateuszPuto** [comment]
For me it was 4 hours. Pretty annoying bug for a deep learning environment.

**Comment by olaviinha** [comment]
Facing the same problem recently.

So far with only one particular, oldish notebook. So not sure if related to notebook or just coincidentally occurred now with that notebook.

**Comment by GabrielOlem** [comment]
Same problem, Any updates?

**Comment by mmarr96** [comment]
same issue, this is absurd

**Comment by Warajet** [comment]
I have been facing this problem for a few months now and it cause me unable to finish my thesis on time! Please fix it asap! This problem is really annoying! What a waste of paying for Google Colab Pro+

**Comment by mmarr96** [comment]
still facing the cut off at 4 hours, might be time to give up with colab

**Comment by filipemesquita** [comment]
This issue has been happening in less than 4 hrs now.

**Comment by ackrds** [comment]
Same issue has happened with me. Though the running time was less than 10 hours in my case.

**Comment by WALLERR** [comment]
The same issue, the session can never run over 4 hours.

**Comment by ackrds** [comment]
I have figured it out. You can import Google's API to download whatever data you want into your session. Drive can be mounted for only so long, but downloaded data remains as long as the session runs.

**Comment by Archicyr** [comment]
same issue here.

**Comment by asal9122** [comment]
Same issue here after 4-5 hours I get disconnected in middle of epochs

Colab pro plus!!!

**Comment by olaviinha** [comment]
Still facing this issue after a month. Just adding that: 

1. it happens also with freshly created notebooks (not just old ones, as was my experience a month ago).

2. Since devs are referencing https://research.google.com/colaboratory/faq.html#drive-timeout in other similar reported issues, I want to state that this same old Drive disconnection happened just now after 4 hours while I was accessing 2 folders in Drive during this session, both of which had 0-5 files.

**Comment by fcx245317735** [comment]
I see! If I train my model for more than about 4 to 5 hours, Colab keeps giving the same error like yours.

**Comment by luccahuguet** [comment]
same problem, please solve this!

**Comment by Ruoqi277** [comment]
Same problem, any solution??

**Comment by gallen881** [comment]
Same issue, waiting for the solution.

**Comment by aaronlifenghan** [comment]
i have the same issue error. I have Pro version of colab, after 6h ish, it reported this error, when the fine-tuning iterations finished as designed, 30 iterations. but then it report this error when it is supposed to carry out a prediction task. Yesterday it happened like this. today I remounted drive and rerun this cell, and it ended with the same error. so the remount did not solve my problem. 
![Screenshot 2023-08-17 at 18 49 44](https://github.com/googlecolab/colabtools/assets/5109847/def00bbe-c0c2-44cc-9f61-9c14da1fb9bd)

**Comment by aaronlifenghan** [comment]
> i have the same issue error. I have Pro version of colab, after 6h ish, it reported this error, when the fine-tuning iterations finished as designed, 30 iterations. but then it report this error when it is supposed to carry out a prediction task. Yesterday it happened like this. today I remounted drive and rerun this cell, and it ended with the same error. so the remount did not solve my problem. ![Screenshot 2023-08-17 at 18 49 44](https://user-images.githubusercontent.com/5109847/261396247-def00bbe-c0c2-44cc-9f61-9c14da1fb9bd.png)

Update in the second day, i.e. today: this error disappeared when I changed 'iteration = 30 to 2' for the fine-tunign step. The run out documentary is available on our project page, uploaded if anyone is interested to check https://github.com/HECTA-UoM/M3/tree/main  still do not know when that error happened yesterday since I have the Pro version and it only cost 5h.

**Comment by Nayrouzzz** [comment]
it happened after running it for only 4 hours !

**Comment by LiuBodan** [comment]
I'm having similar issue, not sure how to solve it

**Comment by mainguyenanhvu** [comment]
I'm having the same issue. I just reset my runtime and lost all variables.

**Comment by mmarr96** [comment]
seeing this error every single day

**Comment by brunotakara** [comment]
I got the same issue after something between 3h30 and 4h, pretty frustating on deep learning applications

**Comment by Waynekagawa** [comment]
I have the same problem on running a PyMC script and a separate PyTorch script. Both of them take >4 hrs to finish. 
Please fix this :( I have to finish my dissertation.

**Comment by simonep1052** [comment]
I face the same issue for weeks. My notebooks encounter this error after approximately 4 hours of usage, and I'm also a Colab+ user.

While I haven't yet discovered a definitive solution to this problem, I did find a workaround that allows me to complete all my training epochs in the end. The method is rather straightforward: I refrain from mounting Google Drive when running my notebooks. To be more specific, I copied all my scripts and files directly to the notebook's local drive, placing them in a directory like `/myscripts`. This is just a new directory located at the same level as `/content`. You could have other directory name. Just make sure not to mount Google Drive while I run training. This approach has proven effective for me. 

Here I provide the statistics of my training info: 
- GPU used: V100 High-RAM
- Training time (including setting up the notebook environment): 14 hours.

**Comment by Sara-hub18** [comment]
> I face the same issue for weeks. My notebooks encounter this error after approximately 4 hours of usage, and I'm also a Colab+ user.
> 
> While I haven't yet discovered a definitive solution to this problem, I did find a workaround that allows me to complete all my training epochs in the end. The method is rather straightforward: I refrain from mounting Google Drive when running my notebooks. To be more specific, I copied all my scripts and files directly to the notebook's local drive, placing them in a directory like `/myscripts`. This is just a new directory located at the same level as `/content`. You could have other directory name. Just make sure not to mount Google Drive while I run training. This approach has proven effective for me.
> 
> Here I provide the statistics of my training info:
> 
> * GPU used: V100 High-RAM
> * Training time (including setting up the notebook environment): 14 hours.

Can you post an image for more explain please? @simonep1052

**Comment by olaviinha** [comment]
You can upload and download files from/to Colab runtime instead of using Drive like so.

<img width="316" alt="image" src="https://github.com/googlecolab/colabtools/assets/50331907/be9eb8ff-6363-4cb5-9563-28639812279f">

<img width="298" alt="image" src="https://github.com/googlecolab/colabtools/assets/50331907/8ce88b61-9b76-4020-bce1-b24ee7860ffe">

**Comment by perceptionisfun** [comment]
I found a way to solve this issue. Apparently this is caused by a google drive bug. I copied all my files from google drive to google cloud storage and then loaded my data from google cloud storage to colab.

here is how you can copy your files from google drive to google cloud storage (you can also just directly upload your files to google cloud storage):

https://stackoverflow.com/questions/48122091/copy-file-from-google-drive-to-google-cloud-storage-within-google

here is how you can load your data from google could storage:

https://stackoverflow.com/questions/66938971/is-there-a-way-to-use-the-data-from-google-cloud-storage-directly-in-colab

hope this helps!!

**Comment by simonep1052** [comment]
> > I face the same issue for weeks. My notebooks encounter this error after approximately 4 hours of usage, and I'm also a Colab+ user.
> > While I haven't yet discovered a definitive solution to this problem, I did find a workaround that allows me to complete all my training epochs in the end. The method is rather straightforward: I refrain from mounting Google Drive when running my notebooks. To be more specific, I copied all my scripts and files directly to the notebook's local drive, placing them in a directory like `/myscripts`. This is just a new directory located at the same level as `/content`. You could have other directory name. Just make sure not to mount Google Drive while I run training. This approach has proven effective for me.
> > Here I provide the statistics of my training info:
> > 
> > * GPU used: V100 High-RAM
> > * Training time (including setting up the notebook environment): 14 hours.
> 
> Can you post an image for more explain please? @simonep1052

> 

Just like @olaviinha and @perceptionisfun mentioned. Here I summarize the steps for completing my training, which should achieve the same result as their solutions.

1. Open my `.ipynb` notebook.
2. Mount Google Drive.

3. Utilize the `!cp sourceFileName -R targetFolderPath` command to copy the necessary files from my Google Drive to Google Cloud Storage. In my specific case, I employ `!cp '/content/drive/MyDrive/Colab Notebooks/project1/' -R '/project1/'`. You can observe the copied files within the directory in the image below:
  
![image](https://github.com/googlecolab/colabtools/assets/119632840/13cc353b-c9f7-4af7-aec4-e20c8117e2e4)
  At some points, maybe it is better to copy files to the `content` folder for avoiding further problems.

4. Unmount Google Drive by:
  ```
  from google.colab import drive
  drive.flush_and_unmount()
  ```
5. Start running my codes for training on my notebook.
6. Once the training is completed and confirmed, if you wish to download the newly generated files (such as trained weights file) from Google Cloud Storage, simply remount Google Drive and utilize the `!cp sourceFileName -R targetFolderPath` command again. (For this step, other people's methods might be better but I have not tried.)

*Please note that this approach is simply a means to complete my training without encountering the issue and does not resolve the OSError: [Errno 107] problem.

**Comment by rafaelglater** [comment]
It has been 8 months since the issue was opened and this problem persists...

**Comment by josem7** [comment]
I hope they fix it soon. It's incredibly annoying to have a Colab running for hours, only to encounter this problem, having to restart the whole process, wasting time and money.

**Comment by luccahuguet** [comment]
You should never run it online. Just copy everything to the local environment and disconnect the drive. 

Works like a charm. 

Unfortunately, this is the better way to deal with this bug

**Comment by zarifaziz** [comment]
I'm getting the same problem. Waiting for a solution.

I'm cancelling my Colab Pro+ account now and moving over to GCP.

**Comment by Hongchenglong** [comment]
I'm getting the same problem. Waiting for a solution.

**Comment by horacemtb** [comment]
I've been struggling with the same problem for the last few days. Each time it pops up after 4 hours of training or so and I lose all my training progress. It's a waste of computing units.

It doesn't seem to be related to a user's subscription or anything. I just bought 500 computing units on pay-as-you-go plan without upgrading to colab pro.

**As a workaround**, get an s3 bucket from some cloud provider, upload all the files you need to your bucket, then in Google Colab use boto3 client to connect to your s3 storage and download the necessary files to Colab runtime instead of mounting your Google Drive. The download is superfast using boto3, much faster than the method suggested by @olaviinha, which could take hours depending on the size of your file(s). The downside is that you have to download and possibly unzip the files each time, but it's just a couple of cells you have to execute in your notebook. At least it's better than losing your progress every single time.

Also, what seems to be the problem with fixing this bug? The issue has been there since February. You keep charging users but the service is unsatisfactory.

**Comment by jinzzasol** [comment]
Same issue here.

**Comment by dutking** [comment]
Same issue - waste of units

**Comment by leostratus** [comment]
This severely limits my use of CoLab. I've a paid subscription as well. What is the point if we can't have longer running notebooks including using drive for our data source? Although I've tried to slim down my training and inference into as fast-running and efficient as possible, once I get to 10k samples to train on in any project, no matter how small the batch sizes or how much normalization I use, the training must take several hours or more. If drive keeps disconnecting then there is really little advantage for me to stay in the Google Ecosystem for something like this. I can't recommend CoLab as an easy to use tool for when I handoff client projects anymore either. Disappointing for Google, because I _was_ recommending folks subscribe if they planned to keep improving their dataset and retraining their models without me. 

I'd really love to see some input in this thread about how this bug is triaged relative to others and where it is in the queue; I have a strong suspicion that the majority of CoLab subscribers are students and _not_ folks doing production level machine learning applications, and this is the kind of limitation that is the reason why us applied ML folks aren't using it.

**Comment by rmcpantoja** [comment]
Same problem since many Monts so far in free colab. Any updates?

**Comment by brunotakara** [comment]
Colab has some limitations on runtime, even with the paid version it disconnects after a while, so it is not possible to train a model if it takes more than X hours (which can vary from 4 to 9 hours, even though they say it runs for 12h+. Also, when their virtual machines are on demand, they priorize users who subscribed for better plans, so you most likely will get disconnected from a VM. I got disconnected once, while my trains were taking something like 3-4 minutes, then after reconnecting and running it again, it took something like 12 hours for the same task :|

**Comment by olaviinha** [comment]
> Colab has some limitations on runtime, even with the paid version it disconnects after a while, so it is not possible to train a model if it takes more than X hours (which can vary from 4 to 9 hours, even though they say it runs for 12h+. Also, when their virtual machines are on demand, they priorize users who subscribed for better plans, so you most likely will get disconnected from a VM. I got disconnected once, while my trains were taking something like 3-4 minutes, then after reconnecting and running it again, it took something like 12 hours for the same task :|

This issue is not about the runtime disconnecting.

**Comment by brunotakara** [comment]
> > Colab has some limitations on runtime, even with the paid version it disconnects after a while, so it is not possible to train a model if it takes more than X hours (which can vary from 4 to 9 hours, even though they say it runs for 12h+. Also, when their virtual machines are on demand, they priorize users who subscribed for better plans, so you most likely will get disconnected from a VM. I got disconnected once, while my trains were taking something like 3-4 minutes, then after reconnecting and running it again, it took something like 12 hours for the same task :|
> 
> This issue is not about the runtime disconnecting.

I tried downloading the files to colab runtime as you mentioned and got the runtime error after some hours training, so on one side there is the endpoint disconnection and on the other side there is the runtime disconnection

**Comment by Armangdi** [comment]
Same issue

**Comment by hartwoolery** [comment]
Same issue - going to have to move away from Colab

**Comment by Sara-hub18** [comment]
What is the alternative to Google Colab?Sent from my phone-------- Original message --------From: Hart Woolery ***@***.***>Date: Mon, Dec 4, 2023, 7:24 PMTo: googlecolab/colabtools ***@***.***>Cc: Sara-hub18 ***@***.***>, Manual ***@***.***>Subject: Re: [googlecolab/colabtools] OSError: [Errno 107] Transport endpoint is not connected (Issue #3441)
Same issue - going to have to move away from Colab

**Comment by Great-Bucket** [comment]
Hi Sara-hub18, I gave up with Colab and am using Amazon EC2. It's more expensive but totally reliable and stable.  AWS Sagemaker is a bit easier to use (and easy to run notebooks in), but it's more expensive.

**Comment by adrianari** [comment]
Facing this problem as well: It really varies how long code is running smoothly until the error appears. Last week, it even happend that - ceteri paribus - the code run through over night without any issues. I then thought the error somehow is solved, started running a second notebook, only for it to throw the error after a couple of hours. (The other code happily run through, even after the second notebook decided to stop) So I am not sure whether this problem can really be influenced by the user.

(Using CPU with added RAM under a Colab Pro subscription. Python 3.10. Error appears regardless of the code, the regularity of reading in / writing data to Drive and used libraries.)

**Comment by adrianari** [comment]
Just trying to see something: How many of you guys work with the "%cd"-command in the files where the error appears?

I ask as I tried a similar solution provided by @olaviinha where I go for a "flash-and-mount" and basically, I get the error thrown immediately (after 1-2 times). I then tried to recreate the error in a new file, where the error is again thrown immediately
```
import time
from google.colab import drive
drive.mount('/content/drive', force_remount = True)
%cd /content/drive/MyDrive/some_subfolder

i = 0
while i < 100:
  time.sleep(1)
  drive.flush_and_unmount()
  time.sleep(1)
  drive.mount('/content/drive')
  time.sleep(1)
  %cd /content/drive/MyDrive/some_subfolder
  print(i)
  i += 1
```
Now, if I uncomment the "% cd"-command completely (meaning at import as well as in the while-loop), the error seems not to be appearing. If I manually interrupt the execution, "KeyboardInterrupted" appears as an error.

If I uncomment one of the occurences of the "% cd"-command, the code runs through as well (in the few iterations I did), but when I for example manually interrupt the execution, the "Transport endpoint is not connected"-error appears instead of "KeyboardInterrupted". 

I thus was wondering whether the command might be problematic just in my case (or even a conincidence) or whether this might be a common ground?

**Comment by olaviinha** [comment]
> Now, if I uncomment the "% cd"-command completely (meaning at import as well as in the while-loop), the error seems not to be appearing. If I manually interrupt the execution, "KeyboardInterrupted" appears as an error.

Did you try with a longer sleep times? I have no idea if `drive.mount()` actually waits for everything regarding Drive mount to be finished or is it possible that e.g. some indexing-type of sorcery still goes on after the execution of `drive.mount()` is seemingly complete, and thus 1 sec sleep times might not be enough to do this kind of flash-and-mount thing?

**Comment by adrianari** [comment]
> > Now, if I uncomment the "% cd"-command completely (meaning at import as well as in the while-loop), the error seems not to be appearing. If I manually interrupt the execution, "KeyboardInterrupted" appears as an error.
> 
> Did you try with a longer sleep times? I have no idea if `drive.mount()` actually waits for everything regarding Drive mount to be finished or is it possible that e.g. some indexing-type of sorcery still goes on after the execution of `drive.mount()` is seemingly complete, and thus 1 sec sleep times might not be enough to do this kind of flash-and-mount thing?

Yep, also did it with 3, 5 and 10 seconds. Behaviour persists: If the "%cd"-command is not present, things run smoothly (even without any time.wait). Whereas the %cd-command it is present, I get thrown the error sooner or later (latest at manual interruption).

Of course, this is not to say this is the answer, just that it might be a possible way to recreate the error, in case others also used the %cd-command in their code (hence my question) and as I saw somewhere in this thread that GC seems to have trouble recreating the error. (I am currently still looking into the long-term behaviour if a %cd-command is not included in the code)

**Comment by GianniGi** [comment]
My drive is "unmounted" every 4 hours or so.
I am running a shell command in a cell
! python script.py
and after 4 hours, it can't write to the output dir anymore!

I have the pro+ plan!

Others with the same problem:

https://www.reddit.com/r/GoogleColab/comments/13ptu48/transport_endpoint_is_not_connected_or_colab/

https://www.reddit.com/r/GoogleColab/comments/16dctyc/training_on_google_colab_pro_is_interrupted_after/

**Comment by SubithaSomadas** [comment]
This below code worked for me .:

import os
# Define the directory name
directory_name = "myscripts"  # Change this to your preferred directory name

# Define the path where you want to create the directory (by default, it's in '/content')
path = '/content/' + directory_name  # Adjust the path if required

# Check if the directory already exists or not
if not os.path.exists(path):
    os.makedirs(path)
    print(f"Directory '{directory_name}' created successfully at '{path}'")
else:
    print(f"Directory '{directory_name}' already exists at '{path}'")


from google.colab import drive
drive.mount('/content/drive')

import shutil

# Define source paths of your files/datasets
source_train_path = "/content/drive/MyDrive/YourDatasetFolder/train"
source_test_path = "/content/drive/MyDrive/YourDatasetFolder/test"
source_val_path = "/content/drive/MyDrive/YourDatasetFolder/val"

# Define the destination path (the directory you created)
destination_path = "/content/myscripts"  # Update this with the directory you created

# Move files/directories to the destination directory
def move_files_to_directory(source, destination):
    try:
        shutil.copytree(source, os.path.join(destination, os.path.basename(source)))
        print(f"Files from {source} moved to {destination} successfully.")
    except FileExistsError:
        print(f"Files already exist at {destination}.")

# Move the datasets to the local directory
move_files_to_directory(source_train_path, destination_path)
move_files_to_directory(source_test_path, destination_path)
move_files_to_directory(source_val_path, destination_path)


# You can set the paths to your new train and test data folders
train_path = "/content/myscripts/train"
test_path = "/content/myscripts/test"
val_path = "/content/myscripts/val"

**Comment by olaviinha** [comment]
> This below code worked for me .: the code create a folder locally and transfer the data to it.redirect the path to the new folder created

How do you copy the checkpoints to Drive, or do you? Would be pretty bummed out after training for 12h only to get disconnected without saving checkpoints outside runtime.

**Comment by GianniGi** [comment]
The Colab has access to drive. The .PT files are saved there. There's no
need to run any cell to give permission to colab,  it's just a permission
that you give to it just once. What are your talking about.

**Comment by olaviinha** [comment]
> The Colab has access to drive. The .PT files are saved there. There's no need to run any cell to give permission to colab, it's just a permission that you give to it just once. What are your talking about.

Nobody has replied to your comment in this thread, good sir. Whatever notifications you hare receiving, are not replies to your comments per se, but to the issue.

**Comment by GianniGi** [comment]
Those comments are completely wrong that's why I answered. He was
explaining how to write to the drive, which makes absolutely no sense,
because the colab has access to the drive and then suddenly loses it.
Absolute madness.

**Comment by LeiYangGH** [comment]
cannot start flask

```python
[2024-01-13 17:39:22 +0000] [10] [ERROR] Socket error processing request.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 66, in handle
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/six.py", line 625, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 49, in handle
    req = six.next(parser)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/parser.py", line 41, in __next__
    self.mesg = self.mesg_class(self.cfg, self.unreader, self.req_count)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/message.py", line 181, in __init__
    super(Request, self).__init__(cfg, unreader)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/message.py", line 54, in __init__
    unused = self.parse(self.unreader)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/message.py", line 230, in parse
    self.headers = self.parse_headers(data[:idx])
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/http/message.py", line 74, in parse_headers
    remote_addr = self.unreader.sock.getpeername()
OSError: [Errno 107] Transport endpoint is not connected

```

**Comment by olaviinha** [comment]
This been happening again with one particular notebook. The notebook saves small amounts (few MB) of data to Drive only by manual user-action, basically every few minutes at fastest possible rate. I.e. it does not write anything to Drive automatically, all the time, or in large amounts. As long as I keep writing that few MB of data to Drive frequently enough (every ~~n minutes), it will end up in this `endpoint is not connected` error after about said 4 hours, and I need to restart runtime.

However, I've found that if I take a longer break from writing data to Drive within those 4 hours (i.e. spend 1-2 not writing any data to Drive), then this problem appears not to occur. It does not appear to occur even after another 4 hours when I keep writing data to Drive again as usual, as long as I took that initial longer break?

I observed this behaviour initially by accident, and have observed it a few times now. I suppose there is still a chance it's some kind of a coincidence, but I doubt it.  Any of this is not meant as advice or workaround, but simply to provide additional details in regards of perhaps colab team one day being able to tackle this issue.

**Comment by deanp70** [comment]
Posting with permission from @cperry-goog - we're collaborating with the Colab team to provide DagsHub Storage as an alternative to GDrive that is more scalable and built for use with large datasets. It's an S3-compatible bucket that has much simpler access controls, and can be mounted easily.

It might help avoid the issues above - [here's a link to an example notebook to try it out](https://colab.research.google.com/#fileId=https%3a%2f%2fdagshub.com%2fDagsHub%2fDagsHubxColab%2fraw%2f7a674bc098ac6a25e78ac89adb3527aee45fe278%2fDagsHub_x_Colab-DagsHub_Storage.ipynb)

We're looking for community feedback, so I'd love to get your input if it helps with the issue at hand.

(If you're curious, [DagsHub](https://dagshub.com/) is a platform for ML teams which is why we think Colab should have a storage solution suitable for ML workloads)

**Comment by peap** [comment]
Thank you everyone for your patience here.

We've released a fix earlier this week that should stop Drive from getting unintentionally unmounted during a session, so errors like `OSError: [Errno 107] Transport endpoint is not connected` should be resolved. If you see such errors again, please create a new issue with a minimal reproducible notebook, and send in-product feedback, as well.

**Comment by Drfengze** [comment]
Still happening, OOM happened and the notebook crash

**Comment by Drfengze** [comment]
Because of this annoying issue, I have to keep watching every run. If any error occurs, the entire program crashes, leaving me unable to do anything else. On top of that, Google Drive keeps causing delays and various naming bugs. I’ve burned through 200 compute units without accomplishing anything.

**Comment by peap** [comment]
This issue wasn't associated with any OOMing issues, as far as I know. Could you please open a new issue with a minimal reproducible notebook, and/or file in-product feedback?

**Comment by asapsmc** [comment]
Still happening. Can't use a colab pro account due to this issue.
