### ISSUE TITLE
Connection failed This account has been blocked from accessing Colab runtimes due to suspected abusive activity. This does not impact access to other Google products. If you believe this has been done in error, review the usage limitations and file an appeal.

### ISSUE THREAD

**Issue by Manjitj** [googlecolab/colabtools#4982]
**Describe the current behavior**
A clear and concise explanation of what is currently happening.

**Describe the expected behavior**
A clear and concise explanation of what you expected to happen.

**What web browser you are using**
(Chrome, Firefox, Safari, etc.)

**Additional context**
Link to a minimal, public, self-contained notebook that reproduces this issue.
 - Share the file using your GitHub account using  File > Save a copy as a GitHub Gist.
 - or Share Drive notebooks using the Share button then 'Get Shareable Link'.

**Comment by Manjitj** [comment]
kindly suggest to fix this problem while I purchased colab pro subscription

**Comment by HARSHEREX-ACX** [comment]
![Screenshot 2024-12-05 121108](https://github.com/user-attachments/assets/9731c69b-7079-451e-a39d-6a7549f07bca)
what is abbusive in this.

i am just training YOLO model.
just purchaced colab pro plus 30 min ago.

**Comment by AzimAlif** [comment]
Same issue. suspended while training a YOLOV8 model.

**Comment by GiGiGitHubye** [comment]
same issue while training Yolo11

**Comment by sunny-pidata** [comment]
same issue occurred  the moment i open a new session.

Please resolve this quickly

**Comment by HARSHEREX-ACX** [comment]
i have some serious work i only have 3 hours. please fix this issue ASAP

**Comment by sunny-pidata** [comment]
me too.^^;;

**Comment by AzimAlif** [comment]
I was in the middle of a Uni project. What else can I use to train the model similar to colab? any suggestions?

**Comment by GQ-Y** [comment]
突然出现的吗？我也是这样？

**Comment by HARSHEREX-ACX** [comment]
> 突然出现的吗？我也是这样？

अंग्रेजी क्यों नहीं बोलते?

**Comment by r00sh1** [comment]
> I was in the middle of a Uni project. What else can I use to train the model similar to colab? any suggestions?

Just login from another gmail account. and use colab

**Comment by GiGiGitHubye** [comment]
> > I was in the middle of a Uni project. What else can I use to train the model similar to colab? any suggestions?
> 
> Just login from another gmail account. and use colab

I opened others 2 account, all banned lol

**Comment by cperry-goog** [comment]
Yesterday ultralytics released 8.3.41, which contained malicious code that could be used for cryptocurrency mining. Automated Colab abuse detection picked this up and began banning unsuspecting ultralytics users who installed 8.3.41 and started training with that version.

We noticed this uptick in bans, but we had made no recent changes to our configs, so were unable to immediately diagnose the issue. Late in the day our Backend TL hopped on while on vacation and root-caused the issue and reported it upstream: https://github.com/ultralytics/ultralytics/issues/18027 - ultralytics subsequently removed 8.3.41 (and briefly, 8.3.42) from PyPI.

We have unbanned all users impacted yesterday, and this issue should be resolved. A big thank you to all users who reported this. We'll have an internal post-mortem to see if we can better avoid these types of attacks in the future.

**Comment by glenn-jocher** [comment]
Thank you @Manjitj and everyone else for bringing this to our attention. We confirm that Ultralytics versions 8.3.41 and 8.3.42 were compromised by a malicious code injection targeting cryptocurrency mining. Both versions have been immediately removed from PyPI.

We have released 8.3.43 which addresses this security issue. Our team is conducting a full security audit and implementing additional safeguards to prevent similar incidents.

We apologize to all affected users and appreciate Google Colab's swift detection of this security breach. We are committed to ensuring the safety and integrity of our package.

**Comment by cperry-goog** [comment]
Thank you @glenn-jocher!!

**Comment by HenrikPetersen** [comment]
Im still not able to connect to a Colab runtime. I filed two appeals yesterday. Is there anything else I can do to get my account unblocked?

**Comment by YurleN** [comment]
I still can't connect to the Colab runtime. 07.12.2024 I have filed an appeal. I worked on a project with YOLOv11 using the ultralitics library. As I understood it, I got into a group of users who downloaded a version of the library with a miner. Now I can't run any notepad with the code. Colab is vital for me to learn.
How can I unlock my account?
