### ISSUE TITLE
colab display incorrect jupyter notebook file name.

### ISSUE THREAD

**Issue by gnoparus** [googlecolab/colabtools#764]
When i open ipython notebook from github using colab, file name seems incorrect.

For example. this public notebook
https://github.com/gnoparus/bualabs/blob/master/nbs/16e-nn-parameter-optimizer.ipynb

I change url in front to colab
https://colab.research.google.com/github/gnoparus/bualabs/blob/master/nbs/16e-nn-parameter-optimizer.ipynb

But in colab, title bar and file name above menu displayed as "16d-neural-network-training-loop.ipynb" which is another notebook in the same path instead of "16e-nn-parameter-optimizer.ipynb". 

Maybe I create this new file 16e by duplicating 16d (16d was created with colab then save to github) that cause meta data duplication or something.

I tried using different google account, Chrome and Firefox, colab still display that file name.

Here is shareable link https://colab.research.google.com/github/gnoparus/bualabs/blob/master/nbs/16e-nn-parameter-optimizer.ipynb

**Comment by gnoparus** [comment]
I found that it's in meta of 16e notebook. And if I didn't save to google drive first, I cannot rename notebook.

{
  "colab": {
    "name": "16d-neural-network-training-loop.ipynb",
    "provenance": []
  },
   .....
  }
}

I also cannot find edit notebook meta menu in colab. Are there any way to edit notebook meta data in colab?

**Comment by LanceNorskog** [comment]
This is still happening.

**Comment by colaboratory-team** [comment]
When you copy or rename a saved colab notebook outside of colab, the colab metadata is preserved, because it is part of the file contents.

In Colab, you can update the title metadata by double-clicking on the title and editing the text, assuming you are looking at an editable view of the notebook.

Outside of colab, you can update the title metadata by opening the notebook with a text editor and changing the metadata directly.

**Comment by LanceNorskog** [comment]
As I said, this is still happening. Either there is an intermittent bug in Colab, or the Google Drive API is letting you down. In fact, I also lost some code edits that I know that I saved repeatedly.
@colaboratory-team

**Comment by FenryrMKIII** [comment]
Same for me.

**Comment by liuxx479** [comment]
same here still, cannot double click the title, or use the dropdown "file" button to change the filename..

**Comment by yoheimiyamoto** [comment]
Same for me.

**Comment by SireneNova** [comment]
This still happens even after the metadata is changed--both the title and url. I don't know why this issue is closed.

**Comment by kaka-lin** [comment]
Same for me

**Comment by KutayAkalin** [comment]
Same for me too

**Comment by NazifaKazimi** [comment]
Now renaming files is solved just double click or enter

**Comment by cmosguy** [comment]
@NazifaKazimi  I am double clicking and it is not letting me change the value at all:

![image](https://user-images.githubusercontent.com/1676382/124479544-0250fa80-dd6c-11eb-8065-7c9ba7f43479.png)

as you can see it is just selecting the workbook name and I want to rename it, but cannot enter any new information after a double click.

**Comment by mz256** [comment]
> This still happens even after the metadata is changed--both the title and url. I don't know why this issue is closed.

If I understand what you did, then this worked for me. After changing the notebook's metadata in GitHub, the correct updated title was shown back in Colab.

**Comment by datasith** [comment]
Still happening in June, 2022. Hack-y solution works as detailed by @mz256.

**Comment by jeffheaton** [comment]
This is still an issue. It confuses my students to no end when using Colab.
